use std::fmt::Write;

use omlua_lua_backend::LuaBackendProfile;
use omlua_lua_ir::{
    LirBinaryOp, LirExpression, LirFunction, LirProgram, LirStatement, LirTerminator, LirUnaryOp,
    LirValue, RuntimeHelper,
};

use crate::{CodegenError, validate::validate};

pub fn emit_lua54(
    program: &LirProgram,
    profile: &LuaBackendProfile,
) -> Result<String, CodegenError> {
    validate(program, profile)?;

    let mut output = String::from("-- Generated by OMLua for Lua 5.4.\n\n");
    for helper in &program.helpers {
        emit_helper(&mut output, *helper);
    }

    output.push_str("local ");
    for (index, function) in program.functions.iter().enumerate() {
        if index != 0 {
            output.push_str(", ");
        }
        write!(output, "f{}", function.id.index()).unwrap();
    }
    output.push_str("\n\n");

    for function in &program.functions {
        emit_function(&mut output, function);
    }
    writeln!(output, "return f{}()", program.entry.index()).unwrap();
    Ok(output)
}

fn emit_helper(output: &mut String, helper: RuntimeHelper) {
    match helper {
        RuntimeHelper::I32DivTrunc => output.push_str(
            "local function __omlua_i32_div_trunc(a, b)\n\
             \x20 local quotient = a / b\n\
             \x20 if quotient < 0 then\n\
             \x20   return math.ceil(quotient)\n\
             \x20 end\n\
             \x20 return math.floor(quotient)\n\
             end\n\n",
        ),
        RuntimeHelper::I32Rem => output.push_str(
            "local function __omlua_i32_rem(a, b)\n\
             \x20 return a - __omlua_i32_div_trunc(a, b) * b\n\
             end\n\n",
        ),
    }
}

fn emit_function(output: &mut String, function: &LirFunction) {
    write!(output, "f{} = function(", function.id.index()).unwrap();
    for (index, parameter) in function.parameters.iter().enumerate() {
        if index != 0 {
            output.push_str(", ");
        }
        write!(output, "v{}", parameter.index()).unwrap();
    }
    output.push_str(")\n");

    let locals: Vec<_> = function
        .locals
        .iter()
        .filter(|local| !local.parameter)
        .collect();
    if !locals.is_empty() {
        output.push_str("  local ");
        for (index, local) in locals.iter().enumerate() {
            if index != 0 {
                output.push_str(", ");
            }
            write!(output, "v{}", local.id.index()).unwrap();
        }
        output.push('\n');
    }
    writeln!(output, "  goto bb{}", function.entry.index()).unwrap();

    for block in &function.blocks {
        writeln!(output, "\n  ::bb{}::", block.id.index()).unwrap();
        for statement in &block.statements {
            match statement {
                LirStatement::Assign { destination, value } => {
                    write!(output, "  v{} = ", destination.index()).unwrap();
                    emit_expression(output, value);
                    output.push('\n');
                }
            }
        }
        emit_terminator(output, &block.terminator);
    }
    output.push_str("end\n\n");
}

fn emit_terminator(output: &mut String, terminator: &LirTerminator) {
    match terminator {
        LirTerminator::Jump { target } => {
            writeln!(output, "  goto bb{}", target.index()).unwrap();
        }
        LirTerminator::Switch {
            discriminant,
            targets,
            otherwise,
        } => {
            for (index, (value, target)) in targets.iter().enumerate() {
                output.push_str(if index == 0 { "  if " } else { "  elseif " });
                emit_expression(output, discriminant);
                output.push_str(" == ");
                emit_integer(output, *value);
                output.push_str(" then\n");
                writeln!(output, "    goto bb{}", target.index()).unwrap();
            }
            if targets.is_empty() {
                writeln!(output, "  goto bb{}", otherwise.index()).unwrap();
            } else {
                output.push_str("  else\n");
                writeln!(output, "    goto bb{}", otherwise.index()).unwrap();
                output.push_str("  end\n");
            }
        }
        LirTerminator::Call {
            callee,
            arguments,
            destination,
            target,
        } => {
            output.push_str("  ");
            if let Some(destination) = destination {
                write!(output, "v{} = ", destination.index()).unwrap();
            }
            write!(output, "f{}(", callee.index()).unwrap();
            for (index, argument) in arguments.iter().enumerate() {
                if index != 0 {
                    output.push_str(", ");
                }
                emit_expression(output, argument);
            }
            output.push_str(")\n");
            writeln!(output, "  goto bb{}", target.index()).unwrap();
        }
        LirTerminator::Branch {
            condition,
            if_true,
            if_false,
        } => {
            output.push_str("  if ");
            emit_expression(output, condition);
            output.push_str(" then\n");
            writeln!(output, "    goto bb{}", if_true.index()).unwrap();
            output.push_str("  else\n");
            writeln!(output, "    goto bb{}", if_false.index()).unwrap();
            output.push_str("  end\n");
        }
        LirTerminator::Return { value } => {
            output.push_str("  return");
            if let Some(value) = value {
                output.push(' ');
                emit_expression(output, value);
            }
            output.push('\n');
        }
        LirTerminator::Raise { message } => {
            output.push_str("  error(");
            emit_string(output, message);
            output.push_str(", 0)\n");
        }
        LirTerminator::Unreachable => {
            output.push_str("  error(\"entered unreachable code\", 0)\n");
        }
    }
}

fn emit_expression(output: &mut String, expression: &LirExpression) {
    match expression {
        LirExpression::Value(LirValue::Local(id)) => {
            write!(output, "v{}", id.index()).unwrap();
        }
        LirExpression::Value(LirValue::Bool(value)) => {
            output.push_str(if *value { "true" } else { "false" })
        }
        LirExpression::Value(LirValue::Integer(value)) => emit_integer(output, *value),
        LirExpression::Unary { op, operand } => {
            output.push('(');
            output.push_str(match op {
                LirUnaryOp::Neg => "-",
                LirUnaryOp::Not => "not ",
            });
            emit_expression(output, operand);
            output.push(')');
        }
        LirExpression::Binary { op, left, right } => {
            output.push('(');
            emit_expression(output, left);
            output.push_str(match op {
                LirBinaryOp::And => " and ",
                LirBinaryOp::Or => " or ",
                LirBinaryOp::Add => " + ",
                LirBinaryOp::Sub => " - ",
                LirBinaryOp::Mul => " * ",
                LirBinaryOp::Eq => " == ",
                LirBinaryOp::Ne => " ~= ",
                LirBinaryOp::Lt => " < ",
                LirBinaryOp::Le => " <= ",
                LirBinaryOp::Gt => " > ",
                LirBinaryOp::Ge => " >= ",
            });
            emit_expression(output, right);
            output.push(')');
        }
        LirExpression::RuntimeCall { helper, arguments } => {
            output.push_str(match helper {
                RuntimeHelper::I32DivTrunc => "__omlua_i32_div_trunc",
                RuntimeHelper::I32Rem => "__omlua_i32_rem",
            });
            output.push('(');
            for (index, argument) in arguments.iter().enumerate() {
                if index != 0 {
                    output.push_str(", ");
                }
                emit_expression(output, argument);
            }
            output.push(')');
        }
    }
}

fn emit_string(output: &mut String, value: &str) {
    output.push('"');
    for character in value.chars() {
        match character {
            '"' => output.push_str("\\\""),
            '\\' => output.push_str("\\\\"),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            character if character.is_control() && (character as u32) <= 0xff => {
                write!(output, "\\x{:02x}", character as u32).unwrap();
            }
            character => output.push(character),
        }
    }
    output.push('"');
}

fn emit_integer(output: &mut String, value: i64) {
    if value == i64::MIN {
        output.push_str("(-9223372036854775807 - 1)");
    } else {
        write!(output, "{value}").unwrap();
    }
}
