use std::{collections::BTreeSet, fmt::Write};

use omlua_lua_backend::LuaBackendProfile;
use omlua_lua_ir::{
    LirBinaryOp, LirExpression, LirFunction, LirLocalId, LirPlace, LirProgram, LirStatement,
    LirTerminator, LirUnaryOp, LirValue, RuntimeHelper,
};

use crate::{CodegenError, validate::validate};

pub fn emit_lua54(
    program: &LirProgram,
    profile: &LuaBackendProfile,
) -> Result<String, CodegenError> {
    validate(program, profile)?;

    let mut functions: Vec<_> = program.functions.iter().collect();
    functions.sort_by_key(|function| function.id);

    let mut output = String::from("-- Generated by OMLua for Lua 5.4.\n\n");
    for helper in &program.helpers {
        emit_helper(&mut output, *helper);
    }

    output.push_str("local ");
    for (index, function) in functions.iter().enumerate() {
        if index != 0 {
            output.push_str(", ");
        }
        write!(output, "f{}", function.id.index()).unwrap();
    }
    output.push_str("\n\n");

    for function in functions {
        emit_function(&mut output, function);
    }
    writeln!(output, "return f{}()", program.entry.index()).unwrap();
    Ok(output)
}

fn emit_helper(output: &mut String, helper: RuntimeHelper) {
    match helper {
        RuntimeHelper::I32DivTrunc => output.push_str(
            "local function __omlua_i32_div_trunc(a, b)\n\
             \x20 local quotient = a / b\n\
             \x20 if quotient < 0 then\n\
             \x20   return math.ceil(quotient)\n\
             \x20 end\n\
             \x20 return math.floor(quotient)\n\
             end\n\n",
        ),
        RuntimeHelper::I32Rem => output.push_str(
            "local function __omlua_i32_rem(a, b)\n\
             \x20 return a - __omlua_i32_div_trunc(a, b) * b\n\
             end\n\n",
        ),
        RuntimeHelper::DeepCopy => output.push_str(
            "local function __omlua_deep_copy(value)\n\
             \x20 if type(value) ~= \"table\" or value.__omlua_ref then\n\
             \x20   return value\n\
             \x20 end\n\
             \x20 local result = {}\n\
             \x20 for i = 1, #value do\n\
             \x20   result[i] = __omlua_deep_copy(value[i])\n\
             \x20 end\n\
             \x20 return result\n\
             end\n\n",
        ),
        RuntimeHelper::RefGet => output.push_str(
            "local function __omlua_ref_get(ref)\n\
             \x20 return ref[1][ref[2]]\n\
             end\n\n",
        ),
        RuntimeHelper::RefSet => output.push_str(
            "local function __omlua_ref_set(ref, value)\n\
             \x20 ref[1][ref[2]] = value\n\
             end\n\n",
        ),
    }
}

fn emit_function(output: &mut String, function: &LirFunction) {
    let addressable: BTreeSet<_> = function
        .locals
        .iter()
        .filter(|local| local.addressable)
        .map(|local| local.id)
        .collect();

    write!(output, "f{} = function(", function.id.index()).unwrap();
    for (index, parameter) in function.parameters.iter().enumerate() {
        if index != 0 {
            output.push_str(", ");
        }
        write!(output, "v{}", parameter.index()).unwrap();
    }
    output.push_str(")\n");

    let ordinary_locals: Vec<_> = function
        .locals
        .iter()
        .filter(|local| !local.parameter && !local.addressable)
        .collect();
    if !ordinary_locals.is_empty() {
        output.push_str("  local ");
        for (index, local) in ordinary_locals.iter().enumerate() {
            if index != 0 {
                output.push_str(", ");
            }
            write!(output, "v{}", local.id.index()).unwrap();
        }
        output.push('\n');
    }
    for local in function
        .locals
        .iter()
        .filter(|local| !local.parameter && local.addressable)
    {
        writeln!(output, "  local v{} = {{nil}}", local.id.index()).unwrap();
    }
    for local in function
        .locals
        .iter()
        .filter(|local| local.parameter && local.addressable)
    {
        writeln!(output, "  v{} = {{v{}}}", local.id.index(), local.id.index()).unwrap();
    }
    writeln!(output, "  goto bb{}", function.entry.index()).unwrap();

    for block in &function.blocks {
        writeln!(output, "\n  ::bb{}::", block.id.index()).unwrap();
        output.push_str("  do\n");
        for statement in &block.statements {
            match statement {
                LirStatement::Assign { destination, value } => {
                    output.push_str("    ");
                    emit_local_lvalue(output, *destination, &addressable);
                    output.push_str(" = ");
                    emit_expression(output, value, &addressable);
                    output.push('\n');
                }
                LirStatement::Store { destination, value } => {
                    emit_store(output, destination, value, &addressable, "    ");
                }
            }
        }
        emit_terminator(output, &block.terminator, &addressable);
        output.push_str("  end\n");
    }
    output.push_str("end\n\n");
}

fn emit_terminator(
    output: &mut String,
    terminator: &LirTerminator,
    addressable: &BTreeSet<LirLocalId>,
) {
    match terminator {
        LirTerminator::Jump { target } => {
            writeln!(output, "    goto bb{}", target.index()).unwrap();
        }
        LirTerminator::Switch {
            discriminant,
            targets,
            otherwise,
        } => {
            for (index, (value, target)) in targets.iter().enumerate() {
                output.push_str(if index == 0 { "    if " } else { "    elseif " });
                emit_expression(output, discriminant, addressable);
                output.push_str(" == ");
                emit_integer(output, *value);
                output.push_str(" then\n");
                writeln!(output, "      goto bb{}", target.index()).unwrap();
            }
            if targets.is_empty() {
                writeln!(output, "    goto bb{}", otherwise.index()).unwrap();
            } else {
                output.push_str("    else\n");
                writeln!(output, "      goto bb{}", otherwise.index()).unwrap();
                output.push_str("    end\n");
            }
        }
        LirTerminator::Call {
            callee,
            arguments,
            destination,
            target,
        } => {
            output.push_str("    ");
            match destination {
                Some(LirPlace::Deref { reference, .. }) => {
                    output.push_str("__omlua_ref_set(");
                    emit_expression(output, reference, addressable);
                    output.push_str(", ");
                    emit_call(output, *callee, arguments, addressable);
                    output.push_str(")\n");
                }
                Some(destination) => {
                    emit_place_lvalue(output, destination, addressable);
                    output.push_str(" = ");
                    emit_call(output, *callee, arguments, addressable);
                    output.push('\n');
                }
                None => {
                    emit_call(output, *callee, arguments, addressable);
                    output.push('\n');
                }
            }
            writeln!(output, "    goto bb{}", target.index()).unwrap();
        }
        LirTerminator::Branch {
            condition,
            if_true,
            if_false,
        } => {
            output.push_str("    if ");
            emit_expression(output, condition, addressable);
            output.push_str(" then\n");
            writeln!(output, "      goto bb{}", if_true.index()).unwrap();
            output.push_str("    else\n");
            writeln!(output, "      goto bb{}", if_false.index()).unwrap();
            output.push_str("    end\n");
        }
        LirTerminator::Return { value } => {
            output.push_str("    return");
            if let Some(value) = value {
                output.push(' ');
                emit_expression(output, value, addressable);
            }
            output.push('\n');
        }
        LirTerminator::Raise { message } => {
            output.push_str("    error(");
            emit_string(output, message);
            output.push_str(", 0)\n");
        }
        LirTerminator::Unreachable => {
            output.push_str("    error(\"entered unreachable code\", 0)\n");
        }
    }
}

fn emit_call(
    output: &mut String,
    callee: omlua_lua_ir::LirFunctionId,
    arguments: &[LirExpression],
    addressable: &BTreeSet<LirLocalId>,
) {
    write!(output, "f{}(", callee.index()).unwrap();
    for (index, argument) in arguments.iter().enumerate() {
        if index != 0 {
            output.push_str(", ");
        }
        emit_expression(output, argument, addressable);
    }
    output.push(')');
}

fn emit_store(
    output: &mut String,
    destination: &LirPlace,
    value: &LirExpression,
    addressable: &BTreeSet<LirLocalId>,
    indent: &str,
) {
    output.push_str(indent);
    match destination {
        LirPlace::Deref { reference, .. } => {
            output.push_str("__omlua_ref_set(");
            emit_expression(output, reference, addressable);
            output.push_str(", ");
            emit_expression(output, value, addressable);
            output.push_str(")\n");
        }
        _ => {
            emit_place_lvalue(output, destination, addressable);
            output.push_str(" = ");
            emit_expression(output, value, addressable);
            output.push('\n');
        }
    }
}

fn emit_local_read(
    output: &mut String,
    id: LirLocalId,
    addressable: &BTreeSet<LirLocalId>,
) {
    write!(output, "v{}", id.index()).unwrap();
    if addressable.contains(&id) {
        output.push_str("[1]");
    }
}

fn emit_local_lvalue(
    output: &mut String,
    id: LirLocalId,
    addressable: &BTreeSet<LirLocalId>,
) {
    emit_local_read(output, id, addressable);
}

fn emit_place_lvalue(
    output: &mut String,
    place: &LirPlace,
    addressable: &BTreeSet<LirLocalId>,
) {
    match place {
        LirPlace::Local(id) => emit_local_lvalue(output, *id, addressable),
        LirPlace::TableField { table, index, .. } => {
            emit_indexable_base(output, table, addressable);
            write!(output, "[{index}]").unwrap();
        }
        LirPlace::EnumField { value, field, .. } => {
            emit_indexable_base(output, value, addressable);
            write!(output, "[{}]", field + 2).unwrap();
        }
        LirPlace::Deref { .. } => {
            unreachable!("dereference stores are emitted through __omlua_ref_set")
        }
    }
}

fn emit_reference(
    output: &mut String,
    place: &LirPlace,
    addressable: &BTreeSet<LirLocalId>,
) {
    match place {
        LirPlace::Local(id) => {
            debug_assert!(addressable.contains(id));
            write!(output, "{{v{}, 1, __omlua_ref = true}}", id.index()).unwrap();
        }
        LirPlace::TableField { table, index, .. } => {
            output.push('{');
            emit_expression(output, table, addressable);
            write!(output, ", {index}, __omlua_ref = true}}").unwrap();
        }
        LirPlace::EnumField { value, field, .. } => {
            output.push('{');
            emit_expression(output, value, addressable);
            write!(output, ", {}, __omlua_ref = true}}", field + 2).unwrap();
        }
        LirPlace::Deref { reference, .. } => {
            // &*r is the same address as r. Reusing the descriptor also preserves
            // reference identity when a reborrow is stored in another aggregate.
            emit_expression(output, reference, addressable);
        }
    }
}

fn emit_expression(
    output: &mut String,
    expression: &LirExpression,
    addressable: &BTreeSet<LirLocalId>,
) {
    match expression {
        LirExpression::Value(LirValue::Local(id)) => emit_local_read(output, *id, addressable),
        LirExpression::Value(LirValue::Bool(value)) => {
            output.push_str(if *value { "true" } else { "false" })
        }
        LirExpression::Value(LirValue::Integer(value)) => emit_integer(output, *value),
        LirExpression::Unary { op, operand } => {
            output.push('(');
            output.push_str(match op {
                LirUnaryOp::Neg => "-",
                LirUnaryOp::Not => "not ",
                LirUnaryOp::BitNot => "~",
            });
            emit_expression(output, operand, addressable);
            output.push(')');
        }
        LirExpression::Binary { op, left, right } => {
            output.push('(');
            emit_expression(output, left, addressable);
            output.push_str(match op {
                LirBinaryOp::And => " and ",
                LirBinaryOp::Or => " or ",
                LirBinaryOp::Add => " + ",
                LirBinaryOp::Sub => " - ",
                LirBinaryOp::Mul => " * ",
                LirBinaryOp::Eq => " == ",
                LirBinaryOp::Ne => " ~= ",
                LirBinaryOp::Lt => " < ",
                LirBinaryOp::Le => " <= ",
                LirBinaryOp::Gt => " > ",
                LirBinaryOp::Ge => " >= ",
            });
            emit_expression(output, right, addressable);
            output.push(')');
        }
        LirExpression::RuntimeCall { helper, arguments } => {
            output.push_str(match helper {
                RuntimeHelper::I32DivTrunc => "__omlua_i32_div_trunc",
                RuntimeHelper::I32Rem => "__omlua_i32_rem",
                RuntimeHelper::DeepCopy => "__omlua_deep_copy",
                RuntimeHelper::RefGet => "__omlua_ref_get",
                RuntimeHelper::RefSet => "__omlua_ref_set",
            });
            output.push('(');
            for (index, argument) in arguments.iter().enumerate() {
                if index != 0 {
                    output.push_str(", ");
                }
                emit_expression(output, argument, addressable);
            }
            output.push(')');
        }
        LirExpression::Table { fields } => {
            output.push('{');
            for (index, field) in fields.iter().enumerate() {
                if index != 0 {
                    output.push_str(", ");
                }
                emit_expression(output, field, addressable);
            }
            output.push('}');
        }
        LirExpression::TableGet { table, index, .. } => {
            emit_indexable_base(output, table, addressable);
            write!(output, "[{index}]").unwrap();
        }
        LirExpression::Enum { tag, fields, .. } => {
            output.push('{');
            emit_integer(output, i64::from(*tag));
            for field in fields {
                output.push_str(", ");
                emit_expression(output, field, addressable);
            }
            output.push('}');
        }
        LirExpression::EnumTag { value } => {
            emit_indexable_base(output, value, addressable);
            output.push_str("[1]");
        }
        LirExpression::EnumField { value, field, .. } => {
            emit_indexable_base(output, value, addressable);
            write!(output, "[{}]", field + 2).unwrap();
        }
        LirExpression::Reference { place, .. } => emit_reference(output, place, addressable),
        LirExpression::DerefGet { reference, .. } => {
            output.push_str("__omlua_ref_get(");
            emit_expression(output, reference, addressable);
            output.push(')');
        }
    }
}

fn emit_indexable_base(
    output: &mut String,
    value: &LirExpression,
    addressable: &BTreeSet<LirLocalId>,
) {
    match value {
        LirExpression::Value(LirValue::Local(_))
        | LirExpression::TableGet { .. }
        | LirExpression::EnumTag { .. }
        | LirExpression::EnumField { .. }
        | LirExpression::DerefGet { .. } => emit_expression(output, value, addressable),
        _ => {
            output.push('(');
            emit_expression(output, value, addressable);
            output.push(')');
        }
    }
}

fn emit_string(output: &mut String, value: &str) {
    output.push('"');
    for character in value.chars() {
        match character {
            '"' => output.push_str("\\\""),
            '\\' => output.push_str("\\\\"),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            character if character.is_control() && (character as u32) <= 0xff => {
                write!(output, "\\x{:02x}", character as u32).unwrap();
            }
            character => output.push(character),
        }
    }
    output.push('"');
}

fn emit_integer(output: &mut String, value: i64) {
    if value == i64::MIN {
        output.push_str("(-9223372036854775807 - 1)");
    } else {
        write!(output, "{value}").unwrap();
    }
}
