use omlua_codegen::emit_lua54;
use omlua_lua_backend::LuaBackendProfile;
use omlua_lua_ir::{
    BackendRequirements, LirBinaryOp, LirBlock, LirBlockId, LirExpression, LirFunction,
    LirFunctionId, LirLocal, LirLocalId, LirProgram, LirStatement, LirTerminator, LirValue,
    LirValueKind, RuntimeHelper,
};

#[test]
fn emits_readable_deterministic_lua54() {
    let source = emit_lua54(&constant_program(7), &LuaBackendProfile::lua54()).unwrap();
    assert_eq!(
        source,
        concat!(
            "-- Generated by OMLua for Lua 5.4.\n",
            "\n",
            "local f0\n",
            "\n",
            "f0 = function()\n",
            "  local v0\n",
            "  goto bb0\n",
            "\n",
            "  ::bb0::\n",
            "  v0 = 7\n",
            "  return v0\n",
            "end\n",
            "\n",
            "return f0()\n",
        )
    );
}

#[test]
fn rejects_an_invalid_local_reference_before_emission() {
    let mut program = constant_program(7);
    program.functions[0].blocks[0].terminator = LirTerminator::Return {
        value: Some(local(99)),
    };
    let error = emit_lua54(&program, &LuaBackendProfile::lua54()).unwrap_err();
    assert_eq!(
        error.to_string(),
        "error[OMLUA0003]: function f0, block bb0 references missing local v99"
    );
}

#[test]
fn emits_the_minimum_integer_without_converting_it_to_float() {
    let source = emit_lua54(&constant_program(i64::MIN), &LuaBackendProfile::lua54()).unwrap();
    assert!(source.contains("v0 = (-9223372036854775807 - 1)"));
}

#[cfg(windows)]
#[test]
fn reference_lua54_executes_division_and_remainder_with_rust_semantics() {
    assert_success(&helper_program(RuntimeHelper::I32DivTrunc), "-2\n");
    assert_success(&helper_program(RuntimeHelper::I32Rem), "-1\n");
}

#[cfg(windows)]
#[test]
fn reference_lua54_executes_calls_and_branches() {
    assert_success(&call_and_branch_program(), "42\n");
}

#[cfg(windows)]
#[test]
fn reference_lua54_reports_explicit_failure_paths() {
    assert_failure(
        &failure_program(LirTerminator::Raise {
            message: "attempt to add with overflow".to_owned(),
        }),
        "attempt to add with overflow",
    );
    assert_failure(
        &failure_program(LirTerminator::Unreachable),
        "entered unreachable code",
    );
}

fn constant_program(value: i64) -> LirProgram {
    program(vec![function(
        0,
        vec![local_definition(0, LirValueKind::Integer, false)],
        Vec::new(),
        Some(0),
        vec![LirBlock {
            id: block_id(0),
            statements: vec![assign(0, integer(value))],
            terminator: LirTerminator::Return {
                value: Some(local(0)),
            },
        }],
    )])
}

fn helper_program(helper: RuntimeHelper) -> LirProgram {
    let helpers = match helper {
        RuntimeHelper::I32DivTrunc => vec![RuntimeHelper::I32DivTrunc],
        RuntimeHelper::I32Rem => vec![RuntimeHelper::I32DivTrunc, RuntimeHelper::I32Rem],
    };
    let mut program = program(vec![function(
        0,
        vec![local_definition(0, LirValueKind::Integer, false)],
        Vec::new(),
        Some(0),
        vec![LirBlock {
            id: block_id(0),
            statements: vec![assign(
                0,
                LirExpression::RuntimeCall {
                    helper,
                    arguments: vec![integer(-7), integer(3)],
                },
            )],
            terminator: LirTerminator::Return {
                value: Some(local(0)),
            },
        }],
    )]);
    program.helpers = helpers;
    program
}

fn call_and_branch_program() -> LirProgram {
    let entry = function(
        0,
        vec![
            local_definition(0, LirValueKind::Integer, false),
            local_definition(1, LirValueKind::Integer, false),
            local_definition(2, LirValueKind::Bool, false),
        ],
        Vec::new(),
        Some(0),
        vec![
            LirBlock {
                id: block_id(0),
                statements: vec![
                    assign(1, integer(41)),
                    assign(
                        2,
                        LirExpression::Binary {
                            op: LirBinaryOp::Eq,
                            left: Box::new(local(1)),
                            right: Box::new(integer(41)),
                        },
                    ),
                ],
                terminator: LirTerminator::Branch {
                    condition: local(2),
                    if_true: block_id(1),
                    if_false: block_id(2),
                },
            },
            LirBlock {
                id: block_id(1),
                statements: Vec::new(),
                terminator: LirTerminator::Call {
                    callee: function_id(1),
                    arguments: vec![local(1)],
                    destination: Some(local_id(0)),
                    target: block_id(3),
                },
            },
            LirBlock {
                id: block_id(2),
                statements: vec![assign(0, integer(0))],
                terminator: LirTerminator::Jump {
                    target: block_id(3),
                },
            },
            LirBlock {
                id: block_id(3),
                statements: Vec::new(),
                terminator: LirTerminator::Return {
                    value: Some(local(0)),
                },
            },
        ],
    );
    let add_one = function(
        1,
        vec![
            local_definition(0, LirValueKind::Integer, false),
            local_definition(1, LirValueKind::Integer, true),
        ],
        vec![local_id(1)],
        Some(0),
        vec![LirBlock {
            id: block_id(0),
            statements: vec![assign(
                0,
                LirExpression::Binary {
                    op: LirBinaryOp::Add,
                    left: Box::new(local(1)),
                    right: Box::new(integer(1)),
                },
            )],
            terminator: LirTerminator::Return {
                value: Some(local(0)),
            },
        }],
    );
    program(vec![entry, add_one])
}

fn failure_program(terminator: LirTerminator) -> LirProgram {
    program(vec![function(
        0,
        Vec::new(),
        Vec::new(),
        None,
        vec![LirBlock {
            id: block_id(0),
            statements: Vec::new(),
            terminator,
        }],
    )])
}

fn program(functions: Vec<LirFunction>) -> LirProgram {
    LirProgram {
        entry: function_id(0),
        requirements: BackendRequirements {
            minimum_integer_bits: 64,
            label_jumps: true,
            native_bitwise: false,
        },
        helpers: Vec::new(),
        functions,
    }
}

fn function(
    id: u32,
    locals: Vec<LirLocal>,
    parameters: Vec<LirLocalId>,
    return_local: Option<u32>,
    blocks: Vec<LirBlock>,
) -> LirFunction {
    LirFunction {
        id: function_id(id),
        entry: block_id(0),
        parameters,
        return_local: return_local.map(local_id),
        locals,
        blocks,
    }
}

fn local_definition(id: u32, kind: LirValueKind, parameter: bool) -> LirLocal {
    LirLocal {
        id: local_id(id),
        kind,
        parameter,
    }
}

fn assign(destination: u32, value: LirExpression) -> LirStatement {
    LirStatement::Assign {
        destination: local_id(destination),
        value,
    }
}

fn local(id: u32) -> LirExpression {
    LirExpression::Value(LirValue::Local(local_id(id)))
}

fn integer(value: i64) -> LirExpression {
    LirExpression::Value(LirValue::Integer(value))
}

fn function_id(id: u32) -> LirFunctionId {
    LirFunctionId::new(id)
}

fn local_id(id: u32) -> LirLocalId {
    LirLocalId::new(id)
}

fn block_id(id: u32) -> LirBlockId {
    LirBlockId::new(id)
}

#[cfg(windows)]
fn assert_success(program: &LirProgram, expected_stdout: &str) {
    let output = execute(program);
    assert!(
        output.status.success(),
        "Lua failed:\n{}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(String::from_utf8(output.stdout).unwrap(), expected_stdout);
    assert!(output.stderr.is_empty());
}

#[cfg(windows)]
fn assert_failure(program: &LirProgram, expected_stderr: &str) {
    let output = execute(program);
    assert!(!output.status.success());
    assert!(output.stdout.is_empty());
    let stderr = String::from_utf8(output.stderr).unwrap();
    assert!(
        stderr.contains(expected_stderr),
        "unexpected stderr: {stderr}"
    );
}

#[cfg(windows)]
fn execute(program: &LirProgram) -> std::process::Output {
    use std::{
        fs,
        process::Command,
        sync::atomic::{AtomicU64, Ordering},
    };

    static NEXT_DIRECTORY: AtomicU64 = AtomicU64::new(0);
    let directory = std::env::temp_dir().join(format!(
        "omlua-lua54-{}-{}",
        std::process::id(),
        NEXT_DIRECTORY.fetch_add(1, Ordering::Relaxed)
    ));
    fs::create_dir(&directory).unwrap();
    let program_path = directory.join("program.lua");
    let source = emit_lua54(program, &LuaBackendProfile::lua54()).unwrap();
    fs::write(&program_path, source).unwrap();

    let runner = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join("tests/lua54/run_and_print.lua");
    let output = Command::new(r"C:\msys64\usr\bin\lua.exe")
        .arg(runner)
        .arg(&program_path)
        .output()
        .unwrap();
    fs::remove_dir_all(directory).unwrap();
    output
}
