use omlua_codegen::emit_lua54;
use omlua_ir::{
    AssertKind, BinaryOp, BlockId, CheckedBinaryOp, Constant, FunctionId, LocalId, LocalKind,
    OmBlock, OmFunction, OmLocal, OmProgram, OmType, Operand, Rvalue, Statement, SwitchValue,
    Terminator, UnwindAction,
};
use omlua_lua_backend::{LuaBackendProfile, lower_program};
use omlua_lua_ir::{
    BackendRequirements, LirBinaryOp, LirBlock, LirBlockId, LirExpression, LirFunction,
    LirFunctionId, LirLocal, LirLocalId, LirProgram, LirStatement, LirTerminator, LirValue,
    LirValueKind, RuntimeHelper,
};

#[test]
fn emits_readable_deterministic_lua54() {
    let source = emit_lua54(&constant_program(7), &LuaBackendProfile::lua54()).unwrap();
    assert_eq!(
        source,
        concat!(
            "-- Generated by OMLua for Lua 5.4.\n",
            "\n",
            "local f0\n",
            "\n",
            "f0 = function()\n",
            "  local v0\n",
            "  goto bb0\n",
            "\n",
            "  ::bb0::\n",
            "  do\n",
            "    v0 = 7\n",
            "    return v0\n",
            "  end\n",
            "end\n",
            "\n",
            "return f0()\n",
        )
    );
}

#[test]
fn rejects_an_invalid_local_reference_before_emission() {
    let mut program = constant_program(7);
    program.functions[0].blocks[0].terminator = LirTerminator::Return {
        value: Some(local(99)),
    };
    let error = emit_lua54(&program, &LuaBackendProfile::lua54()).unwrap_err();
    assert_eq!(
        error.to_string(),
        "error[OMLUA0003]: function f0, block bb0 references missing local v99"
    );
}

#[test]
fn rejects_entry_parameters_and_lua54_local_limit_overflow() {
    let mut parameterized = constant_program(7);
    parameterized.functions[0]
        .locals
        .push(local_definition(1, LirValueKind::Integer, true));
    parameterized.functions[0].parameters.push(local_id(1));
    assert_eq!(
        emit_lua54(&parameterized, &LuaBackendProfile::lua54())
            .unwrap_err()
            .to_string(),
        "error[OMLUA0003]: entry function f0 must not have parameters"
    );

    let mut too_many_locals = constant_program(7);
    for id in 1..=200 {
        too_many_locals.functions[0].locals.push(local_definition(
            id,
            LirValueKind::Integer,
            false,
        ));
    }
    assert_eq!(
        emit_lua54(&too_many_locals, &LuaBackendProfile::lua54())
            .unwrap_err()
            .to_string(),
        "error[OMLUA0003]: function f0 declares more than 200 local names"
    );
}

#[test]
fn emits_functions_in_identifier_order() {
    let mut program = call_and_branch_program();
    program.functions.reverse();
    let source = emit_lua54(&program, &LuaBackendProfile::lua54()).unwrap();
    assert!(
        source.starts_with("-- Generated by OMLua for Lua 5.4.\n\nlocal f0, f1\n\nf0 = function()")
    );
}

#[test]
fn emits_the_minimum_integer_without_converting_it_to_float() {
    let source = emit_lua54(&constant_program(i64::MIN), &LuaBackendProfile::lua54()).unwrap();
    assert!(source.contains("v0 = (-9223372036854775807 - 1)"));
}

#[test]
fn emits_and_validates_packed_tables() {
    let program = table_program(1);
    let source = emit_lua54(&program, &LuaBackendProfile::lua54()).unwrap();
    assert!(source.contains("v0 = {20, 22}"));
    assert!(source.contains("v1 = v0[1]"));

    let error = emit_lua54(&table_program(0), &LuaBackendProfile::lua54()).unwrap_err();
    assert_eq!(
        error.to_string(),
        "error[OMLUA0003]: function f0, block bb0 uses zero as a table index"
    );

    let mut scalar_index = table_program(1);
    let LirStatement::Assign { value, .. } = &mut scalar_index.functions[0].blocks[0].statements[1];
    let LirExpression::TableGet { table, .. } = value else {
        unreachable!()
    };
    **table = integer(7);
    assert_eq!(
        emit_lua54(&scalar_index, &LuaBackendProfile::lua54())
            .unwrap_err()
            .to_string(),
        "error[OMLUA0003]: function f0, block bb0 has an invalid type in table indexing"
    );

    let out_of_bounds = table_program(3);
    assert_eq!(
        emit_lua54(&out_of_bounds, &LuaBackendProfile::lua54())
            .unwrap_err()
            .to_string(),
        "error[OMLUA0003]: function f0, block bb0 indexes field 3 of a table with 2 fields"
    );

    let mut wrong_result = table_program(1);
    wrong_result.functions[0].locals[1].kind = LirValueKind::Bool;
    let LirStatement::Assign { value, .. } = &mut wrong_result.functions[0].blocks[0].statements[1];
    let LirExpression::TableGet { result, .. } = value else {
        unreachable!()
    };
    *result = LirValueKind::Bool;
    assert_eq!(
        emit_lua54(&wrong_result, &LuaBackendProfile::lua54())
            .unwrap_err()
            .to_string(),
        "error[OMLUA0003]: function f0, block bb0 declares the wrong result type for table field 1"
    );
}

#[test]
fn reference_lua54_executes_division_and_remainder_with_rust_semantics() {
    assert_success(&helper_program(RuntimeHelper::I32DivTrunc), "-2\n");
    assert_success(&helper_program(RuntimeHelper::I32Rem), "-1\n");
}

#[test]
fn reference_lua54_executes_calls_and_branches() {
    assert_success(&call_and_branch_program(), "42\n");
}

#[test]
fn reference_lua54_reports_explicit_failure_paths() {
    assert_failure(
        &failure_program(LirTerminator::Raise {
            message: "attempt to add with overflow".to_owned(),
        }),
        "attempt to add with overflow",
    );
    assert_failure(
        &failure_program(LirTerminator::Unreachable),
        "entered unreachable code",
    );
}

fn table_program(index: u32) -> LirProgram {
    LirProgram {
        entry: LirFunctionId::new(0),
        requirements: BackendRequirements {
            minimum_integer_bits: 64,
            label_jumps: true,
            native_bitwise: false,
        },
        helpers: vec![],
        functions: vec![LirFunction {
            id: LirFunctionId::new(0),
            entry: LirBlockId::new(0),
            parameters: vec![],
            return_local: None,
            locals: vec![
                local_definition(
                    0,
                    LirValueKind::Table(vec![LirValueKind::Integer, LirValueKind::Integer]),
                    false,
                ),
                local_definition(1, LirValueKind::Integer, false),
            ],
            blocks: vec![LirBlock {
                id: LirBlockId::new(0),
                statements: vec![
                    assign(
                        0,
                        LirExpression::Table {
                            fields: vec![integer(20), integer(22)],
                        },
                    ),
                    assign(
                        1,
                        LirExpression::TableGet {
                            table: Box::new(local(0)),
                            index,
                            result: LirValueKind::Integer,
                        },
                    ),
                ],
                terminator: LirTerminator::Return { value: None },
            }],
        }],
    }
}

#[test]
fn emits_and_validates_enums() {
    let program = enum_program(1, 1);
    let source = emit_lua54(&program, &LuaBackendProfile::lua54()).unwrap();
    assert!(source.contains("v0 = {1, 20, 22}"));
    assert!(source.contains("v1 = v0[1]"));
    assert!(source.contains("v2 = v0[3]"));

    let error = emit_lua54(&enum_program(9, 0), &LuaBackendProfile::lua54()).unwrap_err();
    assert_eq!(
        error.to_string(),
        "error[OMLUA0003]: function f0, block bb0 constructs an enum with tag 9 outside its shape table"
    );

    let mut non_enum_tag = enum_program(1, 0);
    let LirStatement::Assign { value, .. } = &mut non_enum_tag.functions[0].blocks[0].statements[1];
    let LirExpression::EnumTag { value: base } = value else {
        unreachable!()
    };
    **base = integer(7);
    assert_eq!(
        emit_lua54(&non_enum_tag, &LuaBackendProfile::lua54())
            .unwrap_err()
            .to_string(),
        "error[OMLUA0003]: function f0, block bb0 reads the tag of a non-enum value"
    );

    let mut missing_variant = enum_program(1, 0);
    let LirStatement::Assign { value, .. } = &mut missing_variant.functions[0].blocks[0].statements[2];
    let LirExpression::EnumField { variant, .. } = value else {
        unreachable!()
    };
    *variant = 5;
    assert_eq!(
        emit_lua54(&missing_variant, &LuaBackendProfile::lua54())
            .unwrap_err()
            .to_string(),
        "error[OMLUA0003]: function f0, block bb0 reads variant 5 outside the enum shape table"
    );

    let mut beyond_shape = enum_program(1, 0);
    let LirStatement::Assign { value, .. } = &mut beyond_shape.functions[0].blocks[0].statements[2];
    let LirExpression::EnumField { field, .. } = value else {
        unreachable!()
    };
    *field = 2;
    assert_eq!(
        emit_lua54(&beyond_shape, &LuaBackendProfile::lua54())
            .unwrap_err()
            .to_string(),
        "error[OMLUA0003]: function f0, block bb0 reads field 2 beyond the variant shape"
    );

    let mut wrong_result = enum_program(1, 0);
    let LirStatement::Assign { value, .. } = &mut wrong_result.functions[0].blocks[0].statements[2];
    let LirExpression::EnumField { result, .. } = value else {
        unreachable!()
    };
    *result = LirValueKind::Bool;
    assert_eq!(
        emit_lua54(&wrong_result, &LuaBackendProfile::lua54())
            .unwrap_err()
            .to_string(),
        "error[OMLUA0003]: function f0, block bb0 declares the wrong result type for enum field 0"
    );
}

#[test]
fn reference_lua54_executes_enum_construction_tag_and_field_reads() {
    assert_success(&enum_program(1, 1), "22\n");
    assert_success(&enum_program(0, 0), "20\n");
}

fn enum_program(tag: u32, field: u32) -> LirProgram {
    let shapes = vec![
        vec![LirValueKind::Integer],
        vec![LirValueKind::Integer, LirValueKind::Integer],
    ];
    let value_local = local_definition(0, LirValueKind::Enum(shapes.clone()), false);
    let tag_local = local_definition(1, LirValueKind::Integer, false);
    let field_local = local_definition(2, LirValueKind::Integer, false);
    LirProgram {
        entry: LirFunctionId::new(0),
        requirements: BackendRequirements {
            minimum_integer_bits: 64,
            label_jumps: true,
            native_bitwise: false,
        },
        helpers: vec![],
        functions: vec![LirFunction {
            id: LirFunctionId::new(0),
            entry: LirBlockId::new(0),
            parameters: vec![],
            return_local: Some(local_id(2)),
            locals: vec![value_local, tag_local, field_local],
            blocks: vec![LirBlock {
                id: LirBlockId::new(0),
                statements: vec![
                    assign(
                        0,
                        LirExpression::Enum {
                            shapes,
                            tag,
                            fields: if tag == 0 {
                                vec![integer(20)]
                            } else {
                                vec![integer(20), integer(22)]
                            },
                        },
                    ),
                    assign(
                        1,
                        LirExpression::EnumTag {
                            value: Box::new(local(0)),
                        },
                    ),
                    assign(
                        2,
                        LirExpression::EnumField {
                            value: Box::new(local(0)),
                            variant: 1,
                            field,
                            result: LirValueKind::Integer,
                        },
                    ),
                ],
                terminator: LirTerminator::Return {
                    value: Some(local(2)),
                },
            }],
        }],
    }
}

#[test]
fn reference_lua54_executes_hand_built_omir_through_the_whole_backend() {
    assert_omir_success(&binary_omir(BinaryOp::Div, -7, 3), "-2\n");
    assert_omir_success(&binary_omir(BinaryOp::Rem, -7, 3), "-1\n");
    assert_omir_success(&checked_add_omir(40, 2), "42\n");
    assert_omir_success(&signed_switch_omir(), "42\n");
    assert_omir_success(&call_omir(), "42\n");
    assert_omir_failure(
        &checked_add_omir(i32::MAX, 1),
        "attempt to add with overflow",
    );
}

fn binary_omir(op: BinaryOp, left: i32, right: i32) -> OmProgram {
    OmProgram {
        entry: FunctionId::new(0),
        structs: vec![],
        enums: vec![],
        functions: vec![OmFunction {
            id: FunctionId::new(0),
            name: "calculate".to_owned(),
            return_type: OmType::I32,
            parameters: Vec::new(),
            locals: vec![om_local(0, OmType::I32, LocalKind::Return)],
            blocks: vec![OmBlock {
                id: BlockId::new(0),
                statements: vec![Statement::Assign {
                    destination: LocalId::new(0),
                    value: Rvalue::Binary {
                        op,
                        left: Operand::Constant(Constant::I32(left)),
                        right: Operand::Constant(Constant::I32(right)),
                    },
                }],
                terminator: Terminator::Return,
            }],
        }],
    }
}

fn checked_add_omir(left: i32, right: i32) -> OmProgram {
    let left_operand = Operand::Constant(Constant::I32(left));
    let right_operand = Operand::Constant(Constant::I32(right));
    OmProgram {
        entry: FunctionId::new(0),
        structs: vec![],
        enums: vec![],
        functions: vec![OmFunction {
            id: FunctionId::new(0),
            name: "checked_add".to_owned(),
            return_type: OmType::I32,
            parameters: Vec::new(),
            locals: vec![
                om_local(0, OmType::I32, LocalKind::Return),
                om_local(1, OmType::I32, LocalKind::CheckedValue),
                om_local(2, OmType::Bool, LocalKind::CheckedOverflow),
            ],
            blocks: vec![
                OmBlock {
                    id: BlockId::new(0),
                    statements: vec![Statement::CheckedBinary {
                        value: LocalId::new(1),
                        overflow: LocalId::new(2),
                        op: CheckedBinaryOp::Add,
                        left: left_operand.clone(),
                        right: right_operand.clone(),
                    }],
                    terminator: Terminator::Assert {
                        condition: Operand::Move(LocalId::new(2)),
                        expected: false,
                        kind: AssertKind::Overflow {
                            op: BinaryOp::Add,
                            left: left_operand,
                            right: right_operand,
                        },
                        target: BlockId::new(1),
                        unwind: UnwindAction::Continue,
                    },
                },
                OmBlock {
                    id: BlockId::new(1),
                    statements: vec![Statement::Assign {
                        destination: LocalId::new(0),
                        value: Rvalue::Use(Operand::Move(LocalId::new(1))),
                    }],
                    terminator: Terminator::Return,
                },
            ],
        }],
    }
}

fn signed_switch_omir() -> OmProgram {
    OmProgram {
        entry: FunctionId::new(0),
        structs: vec![],
        enums: vec![],
        functions: vec![OmFunction {
            id: FunctionId::new(0),
            name: "signed_switch".to_owned(),
            return_type: OmType::I32,
            parameters: Vec::new(),
            locals: vec![
                om_local(0, OmType::I32, LocalKind::Return),
                om_local(1, OmType::I32, LocalKind::Temporary),
            ],
            blocks: vec![
                OmBlock {
                    id: BlockId::new(0),
                    statements: vec![Statement::Assign {
                        destination: LocalId::new(1),
                        value: Rvalue::Use(Operand::Constant(Constant::I32(-1))),
                    }],
                    terminator: Terminator::SwitchInt {
                        discriminant: Operand::Move(LocalId::new(1)),
                        targets: vec![(SwitchValue(u128::from(u32::MAX)), BlockId::new(1))],
                        otherwise: BlockId::new(2),
                    },
                },
                returning_block(1, 42),
                returning_block(2, 0),
            ],
        }],
    }
}

fn call_omir() -> OmProgram {
    OmProgram {
        entry: FunctionId::new(0),
        structs: vec![],
        enums: vec![],
        functions: vec![
            OmFunction {
                id: FunctionId::new(0),
                name: "entry".to_owned(),
                return_type: OmType::I32,
                parameters: Vec::new(),
                locals: vec![om_local(0, OmType::I32, LocalKind::Return)],
                blocks: vec![
                    OmBlock {
                        id: BlockId::new(0),
                        statements: Vec::new(),
                        terminator: Terminator::Call {
                            callee: FunctionId::new(1),
                            arguments: vec![Operand::Constant(Constant::I32(41))],
                            destination: LocalId::new(0),
                            target: BlockId::new(1),
                            unwind: UnwindAction::Continue,
                        },
                    },
                    OmBlock {
                        id: BlockId::new(1),
                        statements: Vec::new(),
                        terminator: Terminator::Return,
                    },
                ],
            },
            OmFunction {
                id: FunctionId::new(1),
                name: "add_one".to_owned(),
                return_type: OmType::I32,
                parameters: vec![LocalId::new(1)],
                locals: vec![
                    om_local(0, OmType::I32, LocalKind::Return),
                    om_local(1, OmType::I32, LocalKind::Parameter),
                ],
                blocks: vec![OmBlock {
                    id: BlockId::new(0),
                    statements: vec![Statement::Assign {
                        destination: LocalId::new(0),
                        value: Rvalue::Binary {
                            op: BinaryOp::Add,
                            left: Operand::Copy(LocalId::new(1)),
                            right: Operand::Constant(Constant::I32(1)),
                        },
                    }],
                    terminator: Terminator::Return,
                }],
            },
        ],
    }
}

fn returning_block(id: u32, value: i32) -> OmBlock {
    OmBlock {
        id: BlockId::new(id),
        statements: vec![Statement::Assign {
            destination: LocalId::new(0),
            value: Rvalue::Use(Operand::Constant(Constant::I32(value))),
        }],
        terminator: Terminator::Return,
    }
}

fn om_local(id: u32, ty: OmType, kind: LocalKind) -> OmLocal {
    OmLocal {
        id: LocalId::new(id),
        ty,
        kind,
    }
}

fn constant_program(value: i64) -> LirProgram {
    program(vec![function(
        0,
        vec![local_definition(0, LirValueKind::Integer, false)],
        Vec::new(),
        Some(0),
        vec![LirBlock {
            id: block_id(0),
            statements: vec![assign(0, integer(value))],
            terminator: LirTerminator::Return {
                value: Some(local(0)),
            },
        }],
    )])
}

fn helper_program(helper: RuntimeHelper) -> LirProgram {
    let helpers = match helper {
        RuntimeHelper::I32DivTrunc => vec![RuntimeHelper::I32DivTrunc],
        RuntimeHelper::I32Rem => vec![RuntimeHelper::I32DivTrunc, RuntimeHelper::I32Rem],
    };
    let mut program = program(vec![function(
        0,
        vec![local_definition(0, LirValueKind::Integer, false)],
        Vec::new(),
        Some(0),
        vec![LirBlock {
            id: block_id(0),
            statements: vec![assign(
                0,
                LirExpression::RuntimeCall {
                    helper,
                    arguments: vec![integer(-7), integer(3)],
                },
            )],
            terminator: LirTerminator::Return {
                value: Some(local(0)),
            },
        }],
    )]);
    program.helpers = helpers;
    program
}

fn call_and_branch_program() -> LirProgram {
    let entry = function(
        0,
        vec![
            local_definition(0, LirValueKind::Integer, false),
            local_definition(1, LirValueKind::Integer, false),
            local_definition(2, LirValueKind::Bool, false),
        ],
        Vec::new(),
        Some(0),
        vec![
            LirBlock {
                id: block_id(0),
                statements: vec![
                    assign(1, integer(41)),
                    assign(
                        2,
                        LirExpression::Binary {
                            op: LirBinaryOp::Eq,
                            left: Box::new(local(1)),
                            right: Box::new(integer(41)),
                        },
                    ),
                ],
                terminator: LirTerminator::Branch {
                    condition: local(2),
                    if_true: block_id(1),
                    if_false: block_id(2),
                },
            },
            LirBlock {
                id: block_id(1),
                statements: Vec::new(),
                terminator: LirTerminator::Call {
                    callee: function_id(1),
                    arguments: vec![local(1)],
                    destination: Some(local_id(0)),
                    target: block_id(3),
                },
            },
            LirBlock {
                id: block_id(2),
                statements: vec![assign(0, integer(0))],
                terminator: LirTerminator::Jump {
                    target: block_id(3),
                },
            },
            LirBlock {
                id: block_id(3),
                statements: Vec::new(),
                terminator: LirTerminator::Return {
                    value: Some(local(0)),
                },
            },
        ],
    );
    let add_one = function(
        1,
        vec![
            local_definition(0, LirValueKind::Integer, false),
            local_definition(1, LirValueKind::Integer, true),
        ],
        vec![local_id(1)],
        Some(0),
        vec![LirBlock {
            id: block_id(0),
            statements: vec![assign(
                0,
                LirExpression::Binary {
                    op: LirBinaryOp::Add,
                    left: Box::new(local(1)),
                    right: Box::new(integer(1)),
                },
            )],
            terminator: LirTerminator::Return {
                value: Some(local(0)),
            },
        }],
    );
    program(vec![entry, add_one])
}

fn failure_program(terminator: LirTerminator) -> LirProgram {
    program(vec![function(
        0,
        Vec::new(),
        Vec::new(),
        None,
        vec![LirBlock {
            id: block_id(0),
            statements: Vec::new(),
            terminator,
        }],
    )])
}

fn program(functions: Vec<LirFunction>) -> LirProgram {
    LirProgram {
        entry: function_id(0),
        requirements: BackendRequirements {
            minimum_integer_bits: 64,
            label_jumps: true,
            native_bitwise: false,
        },
        helpers: Vec::new(),
        functions,
    }
}

fn function(
    id: u32,
    locals: Vec<LirLocal>,
    parameters: Vec<LirLocalId>,
    return_local: Option<u32>,
    blocks: Vec<LirBlock>,
) -> LirFunction {
    LirFunction {
        id: function_id(id),
        entry: block_id(0),
        parameters,
        return_local: return_local.map(local_id),
        locals,
        blocks,
    }
}

fn local_definition(id: u32, kind: LirValueKind, parameter: bool) -> LirLocal {
    LirLocal {
        id: local_id(id),
        kind,
        parameter,
    }
}

fn assign(destination: u32, value: LirExpression) -> LirStatement {
    LirStatement::Assign {
        destination: local_id(destination),
        value,
    }
}

fn local(id: u32) -> LirExpression {
    LirExpression::Value(LirValue::Local(local_id(id)))
}

fn integer(value: i64) -> LirExpression {
    LirExpression::Value(LirValue::Integer(value))
}

fn function_id(id: u32) -> LirFunctionId {
    LirFunctionId::new(id)
}

fn local_id(id: u32) -> LirLocalId {
    LirLocalId::new(id)
}

fn block_id(id: u32) -> LirBlockId {
    LirBlockId::new(id)
}

fn assert_success(program: &LirProgram, expected_stdout: &str) {
    let output = execute(program);
    assert!(
        output.status.success(),
        "Lua failed:\n{}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(String::from_utf8(output.stdout).unwrap(), expected_stdout);
    assert!(output.stderr.is_empty());
}

fn assert_omir_success(program: &OmProgram, expected_stdout: &str) {
    let profile = LuaBackendProfile::lua54();
    let lir = lower_program(program, &profile).unwrap();
    assert_success(&lir, expected_stdout);
}

fn assert_failure(program: &LirProgram, expected_stderr: &str) {
    let output = execute(program);
    assert!(!output.status.success());
    assert!(output.stdout.is_empty());
    let stderr = String::from_utf8(output.stderr).unwrap();
    assert!(
        stderr.contains(expected_stderr),
        "unexpected stderr: {stderr}"
    );
}

fn assert_omir_failure(program: &OmProgram, expected_stderr: &str) {
    let profile = LuaBackendProfile::lua54();
    let lir = lower_program(program, &profile).unwrap();
    assert_failure(&lir, expected_stderr);
}

fn execute(program: &LirProgram) -> std::process::Output {
    use std::{
        fs,
        process::Command,
        sync::atomic::{AtomicU64, Ordering},
    };

    static NEXT_DIRECTORY: AtomicU64 = AtomicU64::new(0);
    let directory = std::env::temp_dir().join(format!(
        "omlua-lua54-{}-{}",
        std::process::id(),
        NEXT_DIRECTORY.fetch_add(1, Ordering::Relaxed)
    ));
    fs::create_dir(&directory).unwrap();
    let program_path = directory.join("program.lua");
    let source = emit_lua54(program, &LuaBackendProfile::lua54()).unwrap();
    fs::write(&program_path, source).unwrap();

    let runner = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join("tests/lua54/run_and_print.lua");
    let version = Command::new("lua")
        .arg("-v")
        .output()
        .expect("Lua 5.4.8 is required on PATH");
    assert!(version.status.success());
    let version_text = format!(
        "{}{}",
        String::from_utf8_lossy(&version.stdout),
        String::from_utf8_lossy(&version.stderr)
    );
    assert!(version_text.starts_with("Lua 5.4.8 "), "{version_text}");

    let output = Command::new("lua")
        .arg(runner)
        .arg(&program_path)
        .output()
        .unwrap();
    fs::remove_dir_all(directory).unwrap();
    output
}
