-- Generated by OMLua for Lua 5.4.

local f0, f1, f2

f0 = function()
  local v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14
  goto bb0

  ::bb0::
  do
    v1 = f1(1)
    goto bb1
  end

  ::bb1::
  do
    v3 = (v1 == -2)
    v2 = f2(v3)
    goto bb2
  end

  ::bb2::
  do
    v4 = (v2 == 0)
    if v4 then
      goto bb9
    else
      goto bb3
    end
  end

  ::bb3::
  do
    v5 = (v2 == -1)
    v6 = (1 == -2147483648)
    v7 = (v5 and v6)
    if v7 then
      goto bb10
    else
      goto bb4
    end
  end

  ::bb4::
  do
    v8 = f1(-2147483648)
    goto bb5
  end

  ::bb5::
  do
    v10 = (v8 == 2147483647)
    v9 = f2(v10)
    goto bb6
  end

  ::bb6::
  do
    v11 = (v9 == 0)
    if v11 then
      goto bb11
    else
      goto bb7
    end
  end

  ::bb7::
  do
    v12 = (v9 == -1)
    v13 = (1 == -2147483648)
    v14 = (v12 and v13)
    if v14 then
      goto bb12
    else
      goto bb8
    end
  end

  ::bb8::
  do
    return
  end

  ::bb9::
  do
    error("attempt to divide by zero", 0)
  end

  ::bb10::
  do
    error("attempt to divide with overflow", 0)
  end

  ::bb11::
  do
    error("attempt to divide by zero", 0)
  end

  ::bb12::
  do
    error("attempt to divide with overflow", 0)
  end
end

f1 = function(v1)
  local v0
  goto bb0

  ::bb0::
  do
    v0 = (~v1)
    return v0
  end
end

f2 = function(v1)
  local v0
  goto bb0

  ::bb0::
  do
    if v1 then
      goto bb1
    else
      goto bb2
    end
  end

  ::bb1::
  do
    v0 = 1
    goto bb3
  end

  ::bb2::
  do
    v0 = 0
    goto bb3
  end

  ::bb3::
  do
    return v0
  end
end

return f0()
