-- Generated by OMLua for Lua 5.4.

local f0, f1, f2

f0 = function()
  local v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26, v27, v28
  goto bb0

  ::bb0::
  do
    v3 = f1(false, false)
    goto bb1
  end

  ::bb1::
  do
    v2 = (v3 == 10)
    v1 = f2(v2)
    goto bb2
  end

  ::bb2::
  do
    v4 = (v1 == 0)
    if v4 then
      goto bb17
    else
      goto bb3
    end
  end

  ::bb3::
  do
    v5 = (v1 == -1)
    v6 = (1 == -2147483648)
    v7 = (v5 and v6)
    if v7 then
      goto bb18
    else
      goto bb4
    end
  end

  ::bb4::
  do
    v10 = f1(false, true)
    goto bb5
  end

  ::bb5::
  do
    v9 = (v10 == 3)
    v8 = f2(v9)
    goto bb6
  end

  ::bb6::
  do
    v11 = (v8 == 0)
    if v11 then
      goto bb19
    else
      goto bb7
    end
  end

  ::bb7::
  do
    v12 = (v8 == -1)
    v13 = (1 == -2147483648)
    v14 = (v12 and v13)
    if v14 then
      goto bb20
    else
      goto bb8
    end
  end

  ::bb8::
  do
    v17 = f1(true, false)
    goto bb9
  end

  ::bb9::
  do
    v16 = (v17 == 12)
    v15 = f2(v16)
    goto bb10
  end

  ::bb10::
  do
    v18 = (v15 == 0)
    if v18 then
      goto bb21
    else
      goto bb11
    end
  end

  ::bb11::
  do
    v19 = (v15 == -1)
    v20 = (1 == -2147483648)
    v21 = (v19 and v20)
    if v21 then
      goto bb22
    else
      goto bb12
    end
  end

  ::bb12::
  do
    v24 = f1(true, true)
    goto bb13
  end

  ::bb13::
  do
    v23 = (v24 == 10)
    v22 = f2(v23)
    goto bb14
  end

  ::bb14::
  do
    v25 = (v22 == 0)
    if v25 then
      goto bb23
    else
      goto bb15
    end
  end

  ::bb15::
  do
    v26 = (v22 == -1)
    v27 = (1 == -2147483648)
    v28 = (v26 and v27)
    if v28 then
      goto bb24
    else
      goto bb16
    end
  end

  ::bb16::
  do
    return
  end

  ::bb17::
  do
    error("attempt to divide by zero", 0)
  end

  ::bb18::
  do
    error("attempt to divide with overflow", 0)
  end

  ::bb19::
  do
    error("attempt to divide by zero", 0)
  end

  ::bb20::
  do
    error("attempt to divide with overflow", 0)
  end

  ::bb21::
  do
    error("attempt to divide by zero", 0)
  end

  ::bb22::
  do
    error("attempt to divide with overflow", 0)
  end

  ::bb23::
  do
    error("attempt to divide by zero", 0)
  end

  ::bb24::
  do
    error("attempt to divide with overflow", 0)
  end
end

f1 = function(v1, v2)
  local v0, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15
  goto bb0

  ::bb0::
  do
    v3 = 0
    v4 = ((not v1) and v2)
    if v4 then
      goto bb1
    else
      goto bb3
    end
  end

  ::bb1::
  do
    v5 = (v3 + 1)
    v6 = ((v5 < -2147483648) or (v5 > 2147483647))
    if v6 then
      goto bb13
    else
      goto bb2
    end
  end

  ::bb2::
  do
    v3 = v5
    goto bb3
  end

  ::bb3::
  do
    v7 = ((not v1) or v2)
    if v7 then
      goto bb4
    else
      goto bb6
    end
  end

  ::bb4::
  do
    v8 = (v3 + 2)
    v9 = ((v8 < -2147483648) or (v8 > 2147483647))
    if v9 then
      goto bb14
    else
      goto bb5
    end
  end

  ::bb5::
  do
    v3 = v8
    goto bb6
  end

  ::bb6::
  do
    v10 = (v1 and (not v2))
    if v10 then
      goto bb7
    else
      goto bb9
    end
  end

  ::bb7::
  do
    v11 = (v3 + 4)
    v12 = ((v11 < -2147483648) or (v11 > 2147483647))
    if v12 then
      goto bb15
    else
      goto bb8
    end
  end

  ::bb8::
  do
    v3 = v11
    goto bb9
  end

  ::bb9::
  do
    v13 = (v1 or (not v2))
    if v13 then
      goto bb10
    else
      goto bb12
    end
  end

  ::bb10::
  do
    v14 = (v3 + 8)
    v15 = ((v14 < -2147483648) or (v14 > 2147483647))
    if v15 then
      goto bb16
    else
      goto bb11
    end
  end

  ::bb11::
  do
    v3 = v14
    goto bb12
  end

  ::bb12::
  do
    v0 = v3
    return v0
  end

  ::bb13::
  do
    error("attempt to add with overflow", 0)
  end

  ::bb14::
  do
    error("attempt to add with overflow", 0)
  end

  ::bb15::
  do
    error("attempt to add with overflow", 0)
  end

  ::bb16::
  do
    error("attempt to add with overflow", 0)
  end
end

f2 = function(v1)
  local v0
  goto bb0

  ::bb0::
  do
    if v1 then
      goto bb1
    else
      goto bb2
    end
  end

  ::bb1::
  do
    v0 = 1
    goto bb3
  end

  ::bb2::
  do
    v0 = 0
    goto bb3
  end

  ::bb3::
  do
    return v0
  end
end

return f0()
