-- Generated by OMLua for Lua 5.4.

local f0, f1, f2

f0 = function()
  local v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26, v27, v28, v29, v30, v31, v32, v33, v34, v35, v36, v37
  goto bb0

  ::bb0::
  do
    v2 = {0}
    v1 = f1(v2)
    goto bb1
  end

  ::bb1::
  do
    v4 = {1, 10, 22}
    v3 = f1(v4)
    goto bb2
  end

  ::bb2::
  do
    v6 = {2, 21}
    v5 = f1(v6)
    goto bb3
  end

  ::bb3::
  do
    v9 = {3, 4}
    v8 = {3, v9}
    v7 = f1(v8)
    goto bb4
  end

  ::bb4::
  do
    v12 = {1}
    v11 = {4, v12}
    v10 = f1(v11)
    goto bb5
  end

  ::bb5::
  do
    v15 = {0}
    v14 = {4, v15}
    v13 = f1(v14)
    goto bb6
  end

  ::bb6::
  do
    v21 = (v1 + v3)
    v22 = ((v21 < -2147483648) or (v21 > 2147483647))
    if v22 then
      goto bb15
    else
      goto bb7
    end
  end

  ::bb7::
  do
    v20 = v21
    v23 = (v20 + v5)
    v24 = ((v23 < -2147483648) or (v23 > 2147483647))
    if v24 then
      goto bb16
    else
      goto bb8
    end
  end

  ::bb8::
  do
    v19 = v23
    v25 = (v19 + v7)
    v26 = ((v25 < -2147483648) or (v25 > 2147483647))
    if v26 then
      goto bb17
    else
      goto bb9
    end
  end

  ::bb9::
  do
    v18 = v25
    v27 = (v18 + v10)
    v28 = ((v27 < -2147483648) or (v27 > 2147483647))
    if v28 then
      goto bb18
    else
      goto bb10
    end
  end

  ::bb10::
  do
    v17 = v27
    v29 = (v17 + v13)
    v30 = ((v29 < -2147483648) or (v29 > 2147483647))
    if v30 then
      goto bb19
    else
      goto bb11
    end
  end

  ::bb11::
  do
    v16 = v29
    v31 = (v16 + 2147483545)
    v32 = ((v31 < -2147483648) or (v31 > 2147483647))
    if v32 then
      goto bb20
    else
      goto bb12
    end
  end

  ::bb12::
  do
    v34 = (v16 - 102)
    v35 = ((v34 < -2147483648) or (v34 > 2147483647))
    if v35 then
      goto bb21
    else
      goto bb13
    end
  end

  ::bb13::
  do
    v33 = v34
    v36 = (-2147483648 + v33)
    v37 = ((v36 < -2147483648) or (v36 > 2147483647))
    if v37 then
      goto bb22
    else
      goto bb14
    end
  end

  ::bb14::
  do
    return
  end

  ::bb15::
  do
    error("attempt to add with overflow", 0)
  end

  ::bb16::
  do
    error("attempt to add with overflow", 0)
  end

  ::bb17::
  do
    error("attempt to add with overflow", 0)
  end

  ::bb18::
  do
    error("attempt to add with overflow", 0)
  end

  ::bb19::
  do
    error("attempt to add with overflow", 0)
  end

  ::bb20::
  do
    error("attempt to add with overflow", 0)
  end

  ::bb21::
  do
    error("attempt to subtract with overflow", 0)
  end

  ::bb22::
  do
    error("attempt to add with overflow", 0)
  end
end

f1 = function(v1)
  local v0, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12
  goto bb0

  ::bb0::
  do
    v2 = v1[1]
    if v2 == 0 then
      goto bb6
    elseif v2 == 1 then
      goto bb5
    elseif v2 == 2 then
      goto bb4
    elseif v2 == 3 then
      goto bb3
    elseif v2 == 4 then
      goto bb2
    else
      goto bb1
    end
  end

  ::bb1::
  do
    error("entered unreachable code", 0)
  end

  ::bb2::
  do
    v11 = v1[2]
    v12 = v11[1]
    if v12 == 0 then
      goto bb10
    elseif v12 == 1 then
      goto bb9
    else
      goto bb1
    end
  end

  ::bb3::
  do
    v10 = v1[2]
    v0 = f2(v10)
    goto bb11
  end

  ::bb4::
  do
    v7 = v1[2]
    v8 = (v7 * 2)
    v9 = ((v8 < -2147483648) or (v8 > 2147483647))
    if v9 then
      goto bb12
    else
      goto bb8
    end
  end

  ::bb5::
  do
    v3 = v1[2]
    v4 = v1[3]
    v5 = (v3 + v4)
    v6 = ((v5 < -2147483648) or (v5 > 2147483647))
    if v6 then
      goto bb13
    else
      goto bb7
    end
  end

  ::bb6::
  do
    v0 = 0
    goto bb11
  end

  ::bb7::
  do
    v0 = v5
    goto bb11
  end

  ::bb8::
  do
    v0 = v8
    goto bb11
  end

  ::bb9::
  do
    v0 = 2
    goto bb11
  end

  ::bb10::
  do
    v0 = 1
    goto bb11
  end

  ::bb11::
  do
    return v0
  end

  ::bb12::
  do
    error("attempt to multiply with overflow", 0)
  end

  ::bb13::
  do
    error("attempt to add with overflow", 0)
  end
end

f2 = function(v1)
  local v0, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13
  goto bb0

  ::bb0::
  do
    v3 = v1[1]
    v4 = v1[1]
    v5 = (v3 * v4)
    v6 = ((v5 < -2147483648) or (v5 > 2147483647))
    if v6 then
      goto bb4
    else
      goto bb1
    end
  end

  ::bb1::
  do
    v2 = v5
    v8 = v1[2]
    v9 = v1[2]
    v10 = (v8 * v9)
    v11 = ((v10 < -2147483648) or (v10 > 2147483647))
    if v11 then
      goto bb5
    else
      goto bb2
    end
  end

  ::bb2::
  do
    v7 = v10
    v12 = (v2 + v7)
    v13 = ((v12 < -2147483648) or (v12 > 2147483647))
    if v13 then
      goto bb6
    else
      goto bb3
    end
  end

  ::bb3::
  do
    v0 = v12
    return v0
  end

  ::bb4::
  do
    error("attempt to multiply with overflow", 0)
  end

  ::bb5::
  do
    error("attempt to multiply with overflow", 0)
  end

  ::bb6::
  do
    error("attempt to add with overflow", 0)
  end
end

return f0()
