-- Generated by OMLua for Lua 5.4.

local function __omlua_ref_get(ref)
  return ref[1][ref[2]]
end

local f0, f1, f2

f0 = function()
  local v1, v2, v3, v5, v6, v7, v8, v10, v11, v12, v13, v14, v16, v17, v18, v19, v20, v22, v23, v24, v25, v26, v28, v29, v30, v31, v32, v34, v35, v36, v37, v38, v39, v40, v41, v42, v43, v44, v45, v46, v47
  local v4 = {nil}
  local v15 = {nil}
  local v27 = {nil}
  goto bb0

  ::bb0::
  do
    v1 = -1
    v3 = {2, 5}
    v2 = f1(v3)
    goto bb1
  end

  ::bb1::
  do
    v4[1] = v2
    v6 = {v4, 1, __omlua_ref = true}
    v36 = __omlua_ref_get(v6)[1]
    v37 = __omlua_ref_get(v6)[2]
    v38 = (v36 < v37)
    if v38 then
      goto bb22
    else
      goto bb21
    end
  end

  ::bb2::
  do
    v7 = v5[1]
    if v7 == 0 then
      goto bb5
    elseif v7 == 1 then
      goto bb4
    else
      goto bb3
    end
  end

  ::bb3::
  do
    error("entered unreachable code", 0)
  end

  ::bb4::
  do
    v8 = v5[2]
    v1 = v8
    goto bb5
  end

  ::bb5::
  do
    v11 = v1
    v10 = (v11 == 2)
    f2(v10)
    goto bb6
  end

  ::bb6::
  do
    v12 = 0
    v14 = {0, 0}
    v13 = f1(v14)
    goto bb7
  end

  ::bb7::
  do
    v15[1] = v13
    goto bb8
  end

  ::bb8::
  do
    v17 = {v15, 1, __omlua_ref = true}
    v40 = __omlua_ref_get(v17)[1]
    v41 = __omlua_ref_get(v17)[2]
    v42 = (v40 < v41)
    if v42 then
      goto bb25
    else
      goto bb24
    end
  end

  ::bb9::
  do
    v18 = v16[1]
    if v18 == 0 then
      goto bb11
    elseif v18 == 1 then
      goto bb10
    else
      goto bb3
    end
  end

  ::bb10::
  do
    v19 = (v12 + 1)
    v20 = ((v19 < -2147483648) or (v19 > 2147483647))
    if v20 then
      goto bb30
    else
      goto bb12
    end
  end

  ::bb11::
  do
    v23 = v12
    v22 = (v23 == 0)
    f2(v22)
    goto bb13
  end

  ::bb12::
  do
    v12 = v19
    goto bb8
  end

  ::bb13::
  do
    v24 = 0
    v26 = {0, 1}
    v25 = f1(v26)
    goto bb14
  end

  ::bb14::
  do
    v27[1] = v25
    goto bb15
  end

  ::bb15::
  do
    v29 = {v27, 1, __omlua_ref = true}
    v44 = __omlua_ref_get(v29)[1]
    v45 = __omlua_ref_get(v29)[2]
    v46 = (v44 < v45)
    if v46 then
      goto bb28
    else
      goto bb27
    end
  end

  ::bb16::
  do
    v30 = v28[1]
    if v30 == 0 then
      goto bb18
    elseif v30 == 1 then
      goto bb17
    else
      goto bb3
    end
  end

  ::bb17::
  do
    v31 = (v24 + 1)
    v32 = ((v31 < -2147483648) or (v31 > 2147483647))
    if v32 then
      goto bb31
    else
      goto bb19
    end
  end

  ::bb18::
  do
    v35 = v24
    v34 = (v35 == 1)
    f2(v34)
    goto bb20
  end

  ::bb19::
  do
    v24 = v31
    goto bb15
  end

  ::bb20::
  do
    return
  end

  ::bb21::
  do
    v5 = {0}
    goto bb2
  end

  ::bb22::
  do
    v39 = (v36 + 1)
    __omlua_ref_get(v6)[1] = v39
    v5 = {1, v36}
    goto bb2
  end

  ::bb23::
  do
    error("entered unreachable code", 0)
  end

  ::bb24::
  do
    v16 = {0}
    goto bb9
  end

  ::bb25::
  do
    v43 = (v40 + 1)
    __omlua_ref_get(v17)[1] = v43
    v16 = {1, v40}
    goto bb9
  end

  ::bb26::
  do
    error("entered unreachable code", 0)
  end

  ::bb27::
  do
    v28 = {0}
    goto bb16
  end

  ::bb28::
  do
    v47 = (v44 + 1)
    __omlua_ref_get(v29)[1] = v47
    v28 = {1, v44}
    goto bb16
  end

  ::bb29::
  do
    error("entered unreachable code", 0)
  end

  ::bb30::
  do
    error("attempt to add with overflow", 0)
  end

  ::bb31::
  do
    error("attempt to add with overflow", 0)
  end
end

f1 = function(v1)
  local v0
  goto bb0

  ::bb0::
  do
    v0 = v1
    return v0
  end
end

f2 = function(v1)
  local v2, v3, v4, v5, v6, v7
  goto bb0

  ::bb0::
  do
    if v1 then
      goto bb1
    else
      goto bb2
    end
  end

  ::bb1::
  do
    v2 = 1
    goto bb3
  end

  ::bb2::
  do
    v2 = 0
    goto bb3
  end

  ::bb3::
  do
    v3 = v2
    v4 = (v3 == 0)
    if v4 then
      goto bb6
    else
      goto bb4
    end
  end

  ::bb4::
  do
    v5 = (v3 == -1)
    v6 = (100 == -2147483648)
    v7 = (v5 and v6)
    if v7 then
      goto bb7
    else
      goto bb5
    end
  end

  ::bb5::
  do
    return
  end

  ::bb6::
  do
    error("attempt to divide by zero", 0)
  end

  ::bb7::
  do
    error("attempt to divide with overflow", 0)
  end
end

return f0()
