-- Generated by OMLua for Lua 5.4.

local f0, f1

f0 = function()
  local v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24
  goto bb0

  ::bb0::
  do
    v1 = 0
    v3 = {0, 10}
    v2 = f1(v3)
    goto bb1
  end

  ::bb1::
  do
    v4 = v2
    goto bb2
  end

  ::bb2::
  do
    v6 = v4
    v21 = v4[1]
    v22 = v4[2]
    v23 = (v21 < v22)
    if v23 then
      goto bb14
    else
      goto bb13
    end
  end

  ::bb3::
  do
    v7 = v5[1]
    if v7 == 0 then
      goto bb9
    elseif v7 == 1 then
      goto bb5
    else
      goto bb4
    end
  end

  ::bb4::
  do
    error("entered unreachable code", 0)
  end

  ::bb5::
  do
    v8 = v5[2]
    v9 = (v8 == 3)
    if v9 then
      goto bb2
    else
      goto bb6
    end
  end

  ::bb6::
  do
    v10 = (v8 == 7)
    if v10 then
      goto bb9
    else
      goto bb7
    end
  end

  ::bb7::
  do
    v11 = (v1 + v8)
    v12 = ((v11 < -2147483648) or (v11 > 2147483647))
    if v12 then
      goto bb16
    else
      goto bb8
    end
  end

  ::bb8::
  do
    v1 = v11
    goto bb2
  end

  ::bb9::
  do
    v14 = v1
    v15 = (v14 - 17)
    v16 = ((v15 < -2147483648) or (v15 > 2147483647))
    if v16 then
      goto bb17
    else
      goto bb10
    end
  end

  ::bb10::
  do
    v13 = v15
    v17 = (v13 == 0)
    if v17 then
      goto bb18
    else
      goto bb11
    end
  end

  ::bb11::
  do
    v18 = (v13 == -1)
    v19 = (1000 == -2147483648)
    v20 = (v18 and v19)
    if v20 then
      goto bb19
    else
      goto bb12
    end
  end

  ::bb12::
  do
    return
  end

  ::bb13::
  do
    goto bb3
  end

  ::bb14::
  do
    v24 = (v21 + 1)
    v4 = {v24, v22}
    v5 = {1, v24}
    goto bb3
  end

  ::bb15::
  do
    error("entered unreachable code", 0)
  end

  ::bb16::
  do
    error("attempt to add with overflow", 0)
  end

  ::bb17::
  do
    error("attempt to subtract with overflow", 0)
  end

  ::bb18::
  do
    error("attempt to divide by zero", 0)
  end

  ::bb19::
  do
    error("attempt to divide with overflow", 0)
  end
end

f1 = function(v1)
  local v0
  goto bb0

  ::bb0::
  do
    v0 = v1
    return v0
  end
end

return f0()
