-- Generated by OMLua for Lua 5.4.

local f0, f1, f2, f3, f4, f5, f6, f7, f8

f0 = function()
  local v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26, v27, v28
  goto bb0

  ::bb0::
  do
    v1 = f1()
    goto bb1
  end

  ::bb1::
  do
    v2 = v1[1]
    if v2 == 0 then
      goto bb4
    elseif v2 == 1 then
      goto bb3
    else
      goto bb2
    end
  end

  ::bb2::
  do
    error("entered unreachable code", 0)
  end

  ::bb3::
  do
    v11 = v1[2]
    v12 = v11[1]
    v13 = (v12 - -2)
    v14 = ((v13 < -2147483648) or (v13 > 2147483647))
    if v14 then
      goto bb15
    else
      goto bb7
    end
  end

  ::bb4::
  do
    v3 = v1[2]
    v5 = (v3 - 43)
    v6 = ((v5 < -2147483648) or (v5 > 2147483647))
    if v6 then
      goto bb16
    else
      goto bb5
    end
  end

  ::bb5::
  do
    v4 = v5
    v7 = (v4 == 0)
    if v7 then
      goto bb17
    else
      goto bb6
    end
  end

  ::bb6::
  do
    v8 = (v4 == -1)
    v9 = (100 == -2147483648)
    v10 = (v8 and v9)
    if v10 then
      goto bb18
    else
      goto bb7
    end
  end

  ::bb7::
  do
    v15 = f2()
    goto bb8
  end

  ::bb8::
  do
    v16 = v15[1]
    if v16 == 0 then
      goto bb9
    elseif v16 == 1 then
      goto bb10
    else
      goto bb2
    end
  end

  ::bb9::
  do
    v25 = (1 == 0)
    if v25 then
      goto bb19
    else
      goto bb13
    end
  end

  ::bb10::
  do
    v17 = v15[2]
    v19 = (v17 - 18)
    v20 = ((v19 < -2147483648) or (v19 > 2147483647))
    if v20 then
      goto bb20
    else
      goto bb11
    end
  end

  ::bb11::
  do
    v18 = v19
    v21 = (v18 == 0)
    if v21 then
      goto bb21
    else
      goto bb12
    end
  end

  ::bb12::
  do
    v22 = (v18 == -1)
    v23 = (100 == -2147483648)
    v24 = (v22 and v23)
    if v24 then
      goto bb22
    else
      goto bb14
    end
  end

  ::bb13::
  do
    v26 = (1 == -1)
    v27 = (0 == -2147483648)
    v28 = (v26 and v27)
    if v28 then
      goto bb23
    else
      goto bb14
    end
  end

  ::bb14::
  do
    return
  end

  ::bb15::
  do
    error("attempt to subtract with overflow", 0)
  end

  ::bb16::
  do
    error("attempt to subtract with overflow", 0)
  end

  ::bb17::
  do
    error("attempt to divide by zero", 0)
  end

  ::bb18::
  do
    error("attempt to divide with overflow", 0)
  end

  ::bb19::
  do
    error("attempt to divide by zero", 0)
  end

  ::bb20::
  do
    error("attempt to subtract with overflow", 0)
  end

  ::bb21::
  do
    error("attempt to divide by zero", 0)
  end

  ::bb22::
  do
    error("attempt to divide with overflow", 0)
  end

  ::bb23::
  do
    error("attempt to divide with overflow", 0)
  end
end

f1 = function()
  local v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13
  goto bb0

  ::bb0::
  do
    v2 = f3(21)
    goto bb1
  end

  ::bb1::
  do
    v1 = f4(v2)
    goto bb2
  end

  ::bb2::
  do
    v3 = v1[1]
    if v3 == 0 then
      goto bb4
    elseif v3 == 1 then
      goto bb5
    else
      goto bb3
    end
  end

  ::bb3::
  do
    error("entered unreachable code", 0)
  end

  ::bb4::
  do
    v5 = v1[2]
    v7 = f3(v5)
    goto bb6
  end

  ::bb5::
  do
    v4 = v1[2]
    v0 = f5(v4)
    goto bb11
  end

  ::bb6::
  do
    v6 = f4(v7)
    goto bb7
  end

  ::bb7::
  do
    v8 = v6[1]
    if v8 == 0 then
      goto bb8
    elseif v8 == 1 then
      goto bb9
    else
      goto bb3
    end
  end

  ::bb8::
  do
    v10 = v6[2]
    v12 = (v10 + 1)
    v13 = ((v12 < -2147483648) or (v12 > 2147483647))
    if v13 then
      goto bb12
    else
      goto bb10
    end
  end

  ::bb9::
  do
    v9 = v6[2]
    v0 = f5(v9)
    goto bb11
  end

  ::bb10::
  do
    v11 = v12
    v0 = {0, v11}
    goto bb11
  end

  ::bb11::
  do
    return v0
  end

  ::bb12::
  do
    error("attempt to add with overflow", 0)
  end
end

f2 = function()
  local v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11
  goto bb0

  ::bb0::
  do
    v2 = f6(5)
    goto bb1
  end

  ::bb1::
  do
    v1 = f7(v2)
    goto bb2
  end

  ::bb2::
  do
    v3 = v1[1]
    if v3 == 0 then
      goto bb4
    elseif v3 == 1 then
      goto bb5
    else
      goto bb3
    end
  end

  ::bb3::
  do
    error("entered unreachable code", 0)
  end

  ::bb4::
  do
    v4 = v1[2]
    v6 = f6(v4)
    goto bb6
  end

  ::bb5::
  do
    v0 = f8()
    goto bb11
  end

  ::bb6::
  do
    v5 = f7(v6)
    goto bb7
  end

  ::bb7::
  do
    v7 = v5[1]
    if v7 == 0 then
      goto bb8
    elseif v7 == 1 then
      goto bb9
    else
      goto bb3
    end
  end

  ::bb8::
  do
    v8 = v5[2]
    v10 = (v8 - 1)
    v11 = ((v10 < -2147483648) or (v10 > 2147483647))
    if v11 then
      goto bb12
    else
      goto bb10
    end
  end

  ::bb9::
  do
    v0 = f8()
    goto bb11
  end

  ::bb10::
  do
    v9 = v10
    v0 = {1, v9}
    goto bb11
  end

  ::bb11::
  do
    return v0
  end

  ::bb12::
  do
    error("attempt to subtract with overflow", 0)
  end
end

f3 = function(v1)
  local v0, v2, v3, v4, v5, v6
  goto bb0

  ::bb0::
  do
    v2 = (v1 > 10)
    if v2 then
      goto bb1
    else
      goto bb3
    end
  end

  ::bb1::
  do
    v4 = (v1 * 2)
    v5 = ((v4 < -2147483648) or (v4 > 2147483647))
    if v5 then
      goto bb5
    else
      goto bb2
    end
  end

  ::bb2::
  do
    v3 = v4
    v0 = {0, v3}
    goto bb4
  end

  ::bb3::
  do
    v6 = {v1}
    v0 = {1, v6}
    goto bb4
  end

  ::bb4::
  do
    return v0
  end

  ::bb5::
  do
    error("attempt to multiply with overflow", 0)
  end
end

f4 = function(v1)
  local v0, v2, v3, v4, v5
  goto bb0

  ::bb0::
  do
    v2 = v1[1]
    if v2 == 0 then
      goto bb1
    elseif v2 == 1 then
      goto bb2
    else
      goto bb3
    end
  end

  ::bb1::
  do
    v3 = {0, v1[2]}
    v0 = v3
    return v0
  end

  ::bb2::
  do
    v4 = {1, v1[2]}
    v5 = {1, v4}
    v0 = v5
    return v0
  end

  ::bb3::
  do
    error("entered unreachable code", 0)
  end
end

f5 = function(v1)
  local v0
  goto bb0

  ::bb0::
  do
    v0 = {1, v1[2]}
    return v0
  end
end

f6 = function(v1)
  local v0, v2, v3, v4, v5
  goto bb0

  ::bb0::
  do
    v2 = (v1 > 0)
    if v2 then
      goto bb1
    else
      goto bb3
    end
  end

  ::bb1::
  do
    v4 = (v1 * 2)
    v5 = ((v4 < -2147483648) or (v4 > 2147483647))
    if v5 then
      goto bb5
    else
      goto bb2
    end
  end

  ::bb2::
  do
    v3 = v4
    v0 = {1, v3}
    goto bb4
  end

  ::bb3::
  do
    v0 = {0}
    goto bb4
  end

  ::bb4::
  do
    return v0
  end

  ::bb5::
  do
    error("attempt to multiply with overflow", 0)
  end
end

f7 = function(v1)
  local v0, v2, v3, v4, v5
  goto bb0

  ::bb0::
  do
    v2 = v1[1]
    if v2 == 0 then
      goto bb2
    elseif v2 == 1 then
      goto bb1
    else
      goto bb3
    end
  end

  ::bb1::
  do
    v3 = {0, v1[2]}
    v0 = v3
    return v0
  end

  ::bb2::
  do
    v4 = {0}
    v5 = {1, v4}
    v0 = v5
    return v0
  end

  ::bb3::
  do
    error("entered unreachable code", 0)
  end
end

f8 = function()
  local v0
  goto bb0

  ::bb0::
  do
    v0 = {0}
    return v0
  end
end

return f0()
