-- Generated by OMLua for Lua 5.4.

local function __omlua_deep_copy(value)
  if type(value) ~= "table" or value.__omlua_ref then
    return value
  end
  local result = {}
  for i = 1, #value do
    result[i] = __omlua_deep_copy(value[i])
  end
  return result
end

local function __omlua_ref_get(ref)
  return ref[1][ref[2]]
end

local function __omlua_ref_set(ref, value)
  ref[1][ref[2]] = value
end

local f0, f1, f2, f3, f4, f5, f6, f7

f0 = function()
  local v3, v5, v6, v8, v10, v12, v14, v15, v16, v17, v19, v21, v22, v23, v24, v25, v27, v28, v30, v31, v33, v34, v36, v37, v40, v42, v43, v44, v45, v47, v48
  local v1 = {nil}
  local v7 = {nil}
  local v38 = {nil}
  goto bb0

  ::bb0::
  do
    v1[1] = 1
    v3 = {v1, 1, __omlua_ref = true}
    f1(v3)
    goto bb1
  end

  ::bb1::
  do
    v6 = v1[1]
    v5 = (v6 == 42)
    f2(v5)
    goto bb2
  end

  ::bb2::
  do
    v8 = {0}
    v7[1] = {1, 2, v8}
    v10 = {v7, 1, __omlua_ref = true}
    f3(v10)
    goto bb3
  end

  ::bb3::
  do
    v12 = {v7, 1, __omlua_ref = true}
    f4(v12)
    goto bb4
  end

  ::bb4::
  do
    v15 = v7[1][2]
    v14 = (v15 == 5)
    f2(v14)
    goto bb5
  end

  ::bb5::
  do
    v17 = {v7[1], 1, __omlua_ref = true}
    v16 = f5(v17)
    goto bb6
  end

  ::bb6::
  do
    v19 = (v16 == 16)
    f2(v19)
    goto bb7
  end

  ::bb7::
  do
    v22 = v7[1][3][1]
    v21 = (v22 == 13)
    f2(v21)
    goto bb8
  end

  ::bb8::
  do
    v24 = {5}
    v23 = {3, 4, v24}
    v25 = __omlua_deep_copy(v23)
    v25[1] = 99
    v25[3][1] = 77
    v28 = v23[1]
    v27 = (v28 == 3)
    f2(v27)
    goto bb9
  end

  ::bb9::
  do
    v31 = v23[3][1]
    v30 = (v31 == 5)
    f2(v30)
    goto bb10
  end

  ::bb10::
  do
    v34 = v25[1]
    v33 = (v34 == 99)
    f2(v33)
    goto bb11
  end

  ::bb11::
  do
    v37 = v25[3][1]
    v36 = (v37 == 77)
    f2(v36)
    goto bb12
  end

  ::bb12::
  do
    v38[1] = {1, 10}
    v40 = {v38, 1, __omlua_ref = true}
    f6(v40)
    goto bb13
  end

  ::bb13::
  do
    v44 = __omlua_deep_copy(v38[1])
    v43 = f7(v44)
    goto bb14
  end

  ::bb14::
  do
    v42 = (v43 == 11)
    f2(v42)
    goto bb15
  end

  ::bb15::
  do
    v45 = {0}
    v48 = f7(__omlua_deep_copy(v45))
    goto bb16
  end

  ::bb16::
  do
    v47 = (v48 == -1)
    f2(v47)
    goto bb17
  end

  ::bb17::
  do
    return
  end
end

f1 = function(v1)
  goto bb0

  ::bb0::
  do
    __omlua_ref_set(v1, 42)
    return
  end
end

f2 = function(v1)
  local v2, v3, v4, v5, v6, v7
  goto bb0

  ::bb0::
  do
    if v1 then
      goto bb1
    else
      goto bb2
    end
  end

  ::bb1::
  do
    v2 = 1
    goto bb3
  end

  ::bb2::
  do
    v2 = 0
    goto bb3
  end

  ::bb3::
  do
    v3 = v2
    v4 = (v3 == 0)
    if v4 then
      goto bb6
    else
      goto bb4
    end
  end

  ::bb4::
  do
    v5 = (v3 == -1)
    v6 = (100 == -2147483648)
    v7 = (v5 and v6)
    if v7 then
      goto bb7
    else
      goto bb5
    end
  end

  ::bb5::
  do
    return
  end

  ::bb6::
  do
    error("attempt to divide by zero", 0)
  end

  ::bb7::
  do
    error("attempt to divide with overflow", 0)
  end
end

f3 = function(v1)
  local v2, v3, v4, v5, v6, v7, v8, v9, v10
  goto bb0

  ::bb0::
  do
    v2 = (__omlua_ref_get(v1)[1] + 10)
    v3 = ((v2 < -2147483648) or (v2 > 2147483647))
    if v3 then
      goto bb4
    else
      goto bb1
    end
  end

  ::bb1::
  do
    __omlua_ref_get(v1)[1] = v2
    v4 = __omlua_ref_get(v1)[1]
    v5 = __omlua_ref_get(v1)[2]
    v6 = (v4 + v5)
    v7 = ((v6 < -2147483648) or (v6 > 2147483647))
    if v7 then
      goto bb5
    else
      goto bb2
    end
  end

  ::bb2::
  do
    __omlua_ref_get(v1)[3][1] = v6
    v8 = {__omlua_ref_get(v1), 1, __omlua_ref = true}
    v9 = (__omlua_ref_get(v8) + 5)
    v10 = ((v9 < -2147483648) or (v9 > 2147483647))
    if v10 then
      goto bb6
    else
      goto bb3
    end
  end

  ::bb3::
  do
    __omlua_ref_set(v8, v9)
    return
  end

  ::bb4::
  do
    error("attempt to add with overflow", 0)
  end

  ::bb5::
  do
    error("attempt to add with overflow", 0)
  end

  ::bb6::
  do
    error("attempt to add with overflow", 0)
  end
end

f4 = function(v1)
  local v2, v3
  goto bb0

  ::bb0::
  do
    v2 = (__omlua_ref_get(v1)[2] + 3)
    v3 = ((v2 < -2147483648) or (v2 > 2147483647))
    if v3 then
      goto bb2
    else
      goto bb1
    end
  end

  ::bb1::
  do
    __omlua_ref_get(v1)[2] = v2
    return
  end

  ::bb2::
  do
    error("attempt to add with overflow", 0)
  end
end

f5 = function(v1)
  local v0
  goto bb0

  ::bb0::
  do
    v0 = __omlua_ref_get(v1)
    return v0
  end
end

f6 = function(v1)
  local v2, v3, v4, v5
  goto bb0

  ::bb0::
  do
    v2 = __omlua_ref_get(v1)[1]
    if v2 == 0 then
      goto bb4
    elseif v2 == 1 then
      goto bb2
    else
      goto bb1
    end
  end

  ::bb1::
  do
    error("entered unreachable code", 0)
  end

  ::bb2::
  do
    v3 = {__omlua_ref_get(v1), 2, __omlua_ref = true}
    v4 = (__omlua_ref_get(v3) + 1)
    v5 = ((v4 < -2147483648) or (v4 > 2147483647))
    if v5 then
      goto bb5
    else
      goto bb3
    end
  end

  ::bb3::
  do
    __omlua_ref_set(v3, v4)
    goto bb4
  end

  ::bb4::
  do
    return
  end

  ::bb5::
  do
    error("attempt to add with overflow", 0)
  end
end

f7 = function(v1)
  local v0, v2, v3
  goto bb0

  ::bb0::
  do
    v2 = v1[1]
    if v2 == 0 then
      goto bb3
    elseif v2 == 1 then
      goto bb2
    else
      goto bb1
    end
  end

  ::bb1::
  do
    error("entered unreachable code", 0)
  end

  ::bb2::
  do
    v3 = v1[2]
    v0 = v3
    goto bb4
  end

  ::bb3::
  do
    v0 = -1
    goto bb4
  end

  ::bb4::
  do
    return v0
  end
end

return f0()
