-- Generated by OMLua for Lua 5.4.

local f0, f1, f2

f0 = function()
  local v1, v2
  goto bb0

  ::bb0::
  do
    v1 = f1(-5, 2)
    goto bb1
  end

  ::bb1::
  do
    v2 = f2(v1)
    goto bb2
  end

  ::bb2::
  do
    return
  end
end

f1 = function(v1, v2)
  local v0, v3, v4
  goto bb0

  ::bb0::
  do
    v3 = (v1 + v2)
    v4 = ((v3 < -2147483648) or (v3 > 2147483647))
    if v4 then
      goto bb2
    else
      goto bb1
    end
  end

  ::bb1::
  do
    v0 = v3
    return v0
  end

  ::bb2::
  do
    error("attempt to add with overflow", 0)
  end
end

f2 = function(v1)
  local v0, v2, v3
  goto bb0

  ::bb0::
  do
    v2 = (v1 >= 0)
    if v2 then
      goto bb1
    else
      goto bb2
    end
  end

  ::bb1::
  do
    v0 = v1
    goto bb4
  end

  ::bb2::
  do
    v3 = (v1 == -2147483648)
    if v3 then
      goto bb5
    else
      goto bb3
    end
  end

  ::bb3::
  do
    v0 = (-v1)
    goto bb4
  end

  ::bb4::
  do
    return v0
  end

  ::bb5::
  do
    error("attempt to negate with overflow", 0)
  end
end

return f0()
