-- Generated by OMLua for Lua 5.4.

local function __omlua_i32_div_trunc(a, b)
  local quotient = a / b
  if quotient < 0 then
    return math.ceil(quotient)
  end
  return math.floor(quotient)
end

local f0, f1, f2

f0 = function()
  local v1, v3, v4
  goto bb0

  ::bb0::
  do
    v1 = {20, 22}
    v4 = v1
    v3 = f1(v4)
    goto bb1
  end

  ::bb1::
  do
    f2(v3)
    goto bb2
  end

  ::bb2::
  do
    return
  end
end

f1 = function(v1)
  local v0, v2, v3, v4, v5
  goto bb0

  ::bb0::
  do
    v2 = v1[1]
    v3 = v1[2]
    v4 = (v2 + v3)
    v5 = ((v4 < -2147483648) or (v4 > 2147483647))
    if v5 then
      goto bb2
    else
      goto bb1
    end
  end

  ::bb1::
  do
    v0 = v4
    return v0
  end

  ::bb2::
  do
    error("attempt to add with overflow", 0)
  end
end

f2 = function(v1)
  local v2, v3, v4, v5, v6, v7, v8, v9
  goto bb0

  ::bb0::
  do
    v3 = (v1 == 42)
    if v3 then
      goto bb1
    else
      goto bb2
    end
  end

  ::bb1::
  do
    v2 = 1
    goto bb3
  end

  ::bb2::
  do
    v2 = 0
    goto bb3
  end

  ::bb3::
  do
    v5 = v2
    v6 = (v5 == 0)
    if v6 then
      goto bb6
    else
      goto bb4
    end
  end

  ::bb4::
  do
    v7 = (v5 == -1)
    v8 = (42 == -2147483648)
    v9 = (v7 and v8)
    if v9 then
      goto bb7
    else
      goto bb5
    end
  end

  ::bb5::
  do
    v4 = __omlua_i32_div_trunc(42, v5)
    return
  end

  ::bb6::
  do
    error("attempt to divide by zero", 0)
  end

  ::bb7::
  do
    error("attempt to divide with overflow", 0)
  end
end

return f0()
