-- Generated by OMLua for Lua 5.4.

local f0

f0 = function()
  local v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26, v27, v28, v29, v30, v31, v32, v33, v34, v35, v36
  goto bb0

  ::bb0::
  do
    v1 = 0
    v2 = 0
    goto bb1
  end

  ::bb1::
  do
    v4 = v1
    v3 = (v4 < 10)
    if v3 then
      goto bb2
    else
      goto bb7
    end
  end

  ::bb2::
  do
    v5 = (v1 + 1)
    v6 = ((v5 < -2147483648) or (v5 > 2147483647))
    if v6 then
      goto bb19
    else
      goto bb3
    end
  end

  ::bb3::
  do
    v1 = v5
    v8 = v1
    v7 = (v8 == 5)
    if v7 then
      goto bb1
    else
      goto bb4
    end
  end

  ::bb4::
  do
    v10 = v1
    v9 = (v10 == 8)
    if v9 then
      goto bb7
    else
      goto bb5
    end
  end

  ::bb5::
  do
    v11 = v1
    v12 = (v2 + v11)
    v13 = ((v12 < -2147483648) or (v12 > 2147483647))
    if v13 then
      goto bb20
    else
      goto bb6
    end
  end

  ::bb6::
  do
    v2 = v12
    goto bb1
  end

  ::bb7::
  do
    v14 = v2
    goto bb8
  end

  ::bb8::
  do
    v17 = v2
    v16 = (v17 > 100)
    if v16 then
      goto bb9
    else
      goto bb10
    end
  end

  ::bb9::
  do
    v15 = v2
    v21 = (v14 - 22)
    v22 = ((v21 < -2147483648) or (v21 > 2147483647))
    if v22 then
      goto bb21
    else
      goto bb12
    end
  end

  ::bb10::
  do
    v18 = (v2 + 1)
    v19 = ((v18 < -2147483648) or (v18 > 2147483647))
    if v19 then
      goto bb22
    else
      goto bb11
    end
  end

  ::bb11::
  do
    v2 = v18
    goto bb8
  end

  ::bb12::
  do
    v20 = v21
    v23 = (v20 == 0)
    if v23 then
      goto bb23
    else
      goto bb13
    end
  end

  ::bb13::
  do
    v24 = (v20 == -1)
    v25 = (1000 == -2147483648)
    v26 = (v24 and v25)
    if v26 then
      goto bb24
    else
      goto bb14
    end
  end

  ::bb14::
  do
    v28 = (v15 - 100)
    v29 = ((v28 < -2147483648) or (v28 > 2147483647))
    if v29 then
      goto bb25
    else
      goto bb15
    end
  end

  ::bb15::
  do
    v27 = v28
    v30 = (v27 == 0)
    if v30 then
      goto bb26
    else
      goto bb16
    end
  end

  ::bb16::
  do
    v31 = (v27 == -1)
    v32 = (1000 == -2147483648)
    v33 = (v31 and v32)
    if v33 then
      goto bb27
    else
      goto bb17
    end
  end

  ::bb17::
  do
    v34 = v2
    v35 = (v34 - 8)
    v36 = ((v35 < -2147483648) or (v35 > 2147483647))
    if v36 then
      goto bb28
    else
      goto bb18
    end
  end

  ::bb18::
  do
    return
  end

  ::bb19::
  do
    error("attempt to add with overflow", 0)
  end

  ::bb20::
  do
    error("attempt to add with overflow", 0)
  end

  ::bb21::
  do
    error("attempt to subtract with overflow", 0)
  end

  ::bb22::
  do
    error("attempt to add with overflow", 0)
  end

  ::bb23::
  do
    error("attempt to divide by zero", 0)
  end

  ::bb24::
  do
    error("attempt to divide with overflow", 0)
  end

  ::bb25::
  do
    error("attempt to subtract with overflow", 0)
  end

  ::bb26::
  do
    error("attempt to divide by zero", 0)
  end

  ::bb27::
  do
    error("attempt to divide with overflow", 0)
  end

  ::bb28::
  do
    error("attempt to subtract with overflow", 0)
  end
end

return f0()
